import { useState, useMemo, useEffect } from 'react';
import { Card } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Checkbox } from '@/components/ui/checkbox';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
  DialogFooter,
} from '@/components/ui/dialog';
import { DeleteDialog } from '@/components/ui/delete-dialog';
import { Badge } from '@/components/ui/badge';
import {
  Calendar,
  Clock,
  Plus,
  Edit2,
  Trash2,
  AlertTriangle,
  CheckCircle2,
  ChevronLeft,
  ChevronRight,
  Filter,
  User,
  Users,
  MapPin,
  BookOpen,
  LayoutGrid,
  ListFilter,
  Printer,
  Bookmark,
  FileSpreadsheet,
  Layers,
  Copy,
  Info,
  Sparkles,
  UserPlus,
} from 'lucide-react';
import { toast } from 'sonner';
import {
  Batch,
  Subject,
  Teacher,
  TimetableLecture,
  addTimetableLecture,
  updateTimetableLecture,
  deleteTimetableLecture,
  clearAllTimetableLectures,
  validateTimetableLecture,
  getTeachersForSubject,
  getRooms,
  DAY_ORDER_MAP,
  DAYS_OF_WEEK,
  formatTimeRange12h,
  formatTime12h,
  timeToMinutes,
  addMinutesToTime24,
  formatLectureTeachers,
  formatLectureSubjects,
  formatLectureSubjectWithTeachers,
  getLectureTeacherIds,
  getLectureTeacherNames,
} from '@/lib/localStorage';
import {
  DEFAULT_ROOMS,
  DEFAULT_DIVISIONS,
  getWeekInfo,
  getDateForDayInWeek,
} from '@/lib/timetableUtils';
import { TimetablePlannerMatrix } from './TimetablePlannerMatrix';
import { TimetableCopyDayDialog } from './TimetableCopyDayDialog';
import { TimetableDuplicateBatchDialog } from './TimetableDuplicateBatchDialog';
import { TimetableTemplateDialog } from './TimetableTemplateDialog';
import { TimetableCsvImportDialog } from './TimetableCsvImportDialog';
import { TimetablePrintView } from './TimetablePrintView';
import { TimetableAutoGenerateDialog } from './TimetableAutoGenerateDialog';

export interface AdditionalTeacherSubject {
  id: string;
  teacherId: string;
  subjectName: string;
}

export interface LectureSlotForm {
  id: string;
  startTime: string;
  endTime: string;
  subjectName: string;
  teacherId: string;
  additionalAssignments: AdditionalTeacherSubject[];
  roomMode: string;
  customRoom: string;
}

interface AdminTimetableBuilderProps {
  batches: Batch[];
  subjects: Subject[];
  teachers: Teacher[];
  timetableLectures: TimetableLecture[];
  onDataChange: () => void;
}

export const AdminTimetableBuilder = ({
  batches,
  subjects,
  teachers,
  timetableLectures,
  onDataChange,
}: AdminTimetableBuilderProps) => {
  // Navigation / View Tabs
  const [activeView, setActiveView] = useState<'planner' | 'single_batch' | 'printable'>('planner');

  // Academic Years calculation
  const academicYears = useMemo(() => {
    const yearsSet = new Set<string>();
    batches.forEach(b => {
      if (b.year) yearsSet.add(b.year);
    });
    yearsSet.add('2026-27');
    yearsSet.add('2025-26');
    yearsSet.add('2024-25');
    return Array.from(yearsSet).sort().reverse();
  }, [batches]);

  // Primary Selectors
  const [selectedAcademicYear, setSelectedAcademicYear] = useState<string>(
    academicYears[0] || '2026-27'
  );
  const [selectedBatchId, setSelectedBatchId] = useState<string>(
    batches[0]?.id || ''
  );
  const [selectedDivision, setSelectedDivision] = useState<string>('All');

  // Week Selector (defaults to current week)
  const [currentWeekDate, setCurrentWeekDate] = useState<Date>(new Date());
  const weekInfo = useMemo(() => getWeekInfo(currentWeekDate), [currentWeekDate]);

  // Secondary Filters for Single Batch View
  const [filterTeacherId, setFilterTeacherId] = useState<string>('all');
  const [filterSubject, setFilterSubject] = useState<string>('all');
  const [filterRoom, setFilterRoom] = useState<string>('all');
  const [showSunday, setShowSunday] = useState<boolean>(false);

  // Sub-dialog states
  const [copyDayDialogOpen, setCopyDayDialogOpen] = useState<boolean>(false);
  const [copyDaySource, setCopyDaySource] = useState<string>('Monday');
  const [duplicateBatchOpen, setDuplicateBatchOpen] = useState<boolean>(false);
  const [templateDialogOpen, setTemplateDialogOpen] = useState<boolean>(false);
  const [csvImportDialogOpen, setCsvImportDialogOpen] = useState<boolean>(false);
  const [autoGenerateOpen, setAutoGenerateOpen] = useState<boolean>(false);

  // Modal State for Add / Edit Lecture
  const [isDialogOpen, setIsDialogOpen] = useState<boolean>(false);
  const [editingLecture, setEditingLecture] = useState<TimetableLecture | null>(null);

  // Pre-fixed Batch & Day for modal
  const [modalBatch, setModalBatch] = useState<Batch | null>(null);
  const [modalDay, setModalDay] = useState<string>('Monday');

  // Multi-Slot Lecture State for Add/Edit Dialog
  const [formSlots, setFormSlots] = useState<LectureSlotForm[]>([]);
  const [validationError, setValidationError] = useState<string | null>(null);
  const [isSavingLecture, setIsSavingLecture] = useState<boolean>(false);
  const [isClearingAllLectures, setIsClearingAllLectures] = useState<boolean>(false);

  // Sync selectedBatchId if batches load late
  useEffect(() => {
    if (!selectedBatchId && batches.length > 0) {
      setSelectedBatchId(batches[0].id);
    }
  }, [batches, selectedBatchId]);

  // Selected batch object
  const selectedBatch = useMemo(
    () => batches.find(b => b.id === selectedBatchId) || batches[0],
    [batches, selectedBatchId]
  );

  // Configured rooms list
  const [configuredRooms, setConfiguredRooms] = useState<string[]>(() => getRooms());
  useEffect(() => {
    setConfiguredRooms(getRooms());
  }, [timetableLectures, isDialogOpen]);

  // Helper to query eligible teachers for an additional assignment, prioritizing unassigned teachers
  const getEligibleAdditionalTeachers = (
    subj: string,
    currentSlot: LectureSlotForm,
    currentAssignIndex?: number
  ) => {
    if (!subj) return [];
    const eligible = getTeachersForSubject(subj, teachers);
    const assignedIds = new Set<string>();
    if (currentSlot.teacherId) assignedIds.add(currentSlot.teacherId);
    currentSlot.additionalAssignments.forEach((a, idx) => {
      if (idx !== currentAssignIndex && a.teacherId) {
        assignedIds.add(a.teacherId);
      }
    });

    const unassigned = eligible.filter(t => !assignedIds.has(t.id));
    return unassigned.length > 0 ? unassigned : eligible;
  };

  // Helper to update a specific slot in formSlots
  const updateSlot = (index: number, updates: Partial<LectureSlotForm>) => {
    setFormSlots(prev => {
      const next = [...prev];
      next[index] = { ...next[index], ...updates };
      return next;
    });
    setValidationError(null);
  };

  // When primary subject changes for a slot
  const handleSlotSubjectChange = (index: number, newSubject: string) => {
    const eligible = getTeachersForSubject(newSubject, teachers);
    const autoTeacherId = eligible.length === 1 ? eligible[0].id : '';
    updateSlot(index, {
      subjectName: newSubject,
      teacherId: autoTeacherId,
    });
  };

  // Add another teacher to a slot (which also displays Add Another Subject)
  const handleAddTeacherToSlot = (slotIndex: number) => {
    const slot = formSlots[slotIndex];
    if (!slot) return;
    const subj = slot.subjectName;
    const eligible = getEligibleAdditionalTeachers(subj, slot);
    const autoTeacherId = eligible.length === 1 ? eligible[0].id : '';

    const newAssignment: AdditionalTeacherSubject = {
      id: `assign_${Date.now()}_${Math.random().toString(36).substring(2, 5)}`,
      teacherId: autoTeacherId,
      subjectName: subj,
    };

    updateSlot(slotIndex, {
      additionalAssignments: [...slot.additionalAssignments, newAssignment],
    });
  };

  // Add another subject to a slot
  const handleAddSubjectToSlot = (slotIndex: number) => {
    const slot = formSlots[slotIndex];
    if (!slot) return;
    const usedSubjects = new Set<string>([
      slot.subjectName.toLowerCase(),
      ...slot.additionalAssignments.map(a => a.subjectName.toLowerCase()),
    ]);
    const nextSubjectObj = subjects.find(s => !usedSubjects.has(s.name.toLowerCase())) || subjects[0];
    const subj = nextSubjectObj?.name || 'Science';
    const eligible = getEligibleAdditionalTeachers(subj, slot);
    const autoTeacherId = eligible.length === 1 ? eligible[0].id : '';

    const newAssignment: AdditionalTeacherSubject = {
      id: `assign_${Date.now()}_${Math.random().toString(36).substring(2, 5)}`,
      teacherId: autoTeacherId,
      subjectName: subj,
    };

    updateSlot(slotIndex, {
      additionalAssignments: [...slot.additionalAssignments, newAssignment],
    });
  };

  // Remove an additional assignment
  const handleRemoveAdditionalAssignment = (slotIndex: number, assignIndex: number) => {
    const slot = formSlots[slotIndex];
    if (!slot) return;
    const updated = slot.additionalAssignments.filter((_, idx) => idx !== assignIndex);
    updateSlot(slotIndex, { additionalAssignments: updated });
  };

  // Update an additional assignment (teacher or subject)
  const handleUpdateAdditionalAssignment = (
    slotIndex: number,
    assignIndex: number,
    updates: Partial<AdditionalTeacherSubject>
  ) => {
    const slot = formSlots[slotIndex];
    if (!slot) return;
    const nextAssignments = [...slot.additionalAssignments];
    const current = nextAssignments[assignIndex];
    if (!current) return;

    if (updates.subjectName !== undefined && updates.subjectName !== current.subjectName) {
      const eligible = getEligibleAdditionalTeachers(updates.subjectName, slot, assignIndex);
      const autoTeacherId = eligible.length === 1 ? eligible[0].id : '';
      nextAssignments[assignIndex] = {
        ...current,
        ...updates,
        teacherId: autoTeacherId,
      };
    } else {
      nextAssignments[assignIndex] = {
        ...current,
        ...updates,
      };
    }

    updateSlot(slotIndex, { additionalAssignments: nextAssignments });
  };

  // Add another lecture slot to the form (e.g. 4 to 6 PM, then 6 to 8 PM)
  const handleAddSlot = () => {
    const lastSlot = formSlots[formSlots.length - 1];
    const nextStart = lastSlot?.endTime || '18:00';
    const duration = lastSlot
      ? Math.max(30, timeToMinutes(lastSlot.endTime) - timeToMinutes(lastSlot.startTime))
      : 120;
    const nextEnd = addMinutesToTime24(nextStart, duration);

    const defaultSubj = subjects[0]?.name || 'Mathematics';
    const eligible = getTeachersForSubject(defaultSubj, teachers);

    const newSlot: LectureSlotForm = {
      id: `slot_${Date.now()}_${Math.random().toString(36).substring(2, 5)}`,
      startTime: nextStart,
      endTime: nextEnd,
      subjectName: defaultSubj,
      teacherId: eligible.length === 1 ? eligible[0].id : '',
      additionalAssignments: [],
      roomMode: lastSlot?.roomMode || configuredRooms[0] || 'Room 1',
      customRoom: lastSlot?.customRoom || '',
    };

    setFormSlots(prev => [...prev, newSlot]);
    setValidationError(null);
  };

  // Remove a slot from the form
  const handleRemoveSlot = (index: number) => {
    if (formSlots.length <= 1) return;
    setFormSlots(prev => prev.filter((_, i) => i !== index));
    setValidationError(null);
  };

  // Open Add Lecture modal for a specific batch and day (Batch & Day already known)
  const handleOpenAddLecture = (batch: Batch, day: string) => {
    setEditingLecture(null);
    setModalBatch(batch);
    setModalDay(day);
    setValidationError(null);

    const defaultSubject = subjects[0]?.name || 'Mathematics';
    const eligible = getTeachersForSubject(defaultSubject, teachers);

    setFormSlots([
      {
        id: `slot_${Date.now()}`,
        startTime: '16:00',
        endTime: '18:00',
        subjectName: defaultSubject,
        teacherId: eligible.length === 1 ? eligible[0].id : '',
        additionalAssignments: [],
        roomMode: configuredRooms[0] || 'Room 1',
        customRoom: '',
      },
    ]);

    setIsDialogOpen(true);
  };

  // Open Edit Lecture modal
  const handleOpenEditLecture = (lecture: TimetableLecture) => {
    const lectureBatch = batches.find(b => b.id === lecture.batchId) || {
      id: lecture.batchId,
      name: lecture.batchName,
      year: '',
    };
    setEditingLecture(lecture);
    setModalBatch(lectureBatch);
    setModalDay(lecture.day);
    setValidationError(null);

    const tIds = getLectureTeacherIds(lecture);
    const primaryId = tIds[0] || lecture.teacherId || '';
    const additionalIds = tIds.slice(1);

    const primarySubject = lecture.teacherSubjectMap?.[primaryId] || lecture.subjectNames?.[0] || lecture.subjectName;

    const additionalAssignments: AdditionalTeacherSubject[] = additionalIds.map((tId, idx) => {
      const coSubj = lecture.teacherSubjectMap?.[tId] || lecture.subjectNames?.[idx + 1] || primarySubject;
      return {
        id: `assign_${tId}_${idx}`,
        teacherId: tId,
        subjectName: coSubj,
      };
    });

    setFormSlots([
      {
        id: `slot_${lecture.timetableId}`,
        startTime: lecture.startTime,
        endTime: lecture.endTime,
        subjectName: primarySubject,
        teacherId: primaryId,
        additionalAssignments,
        roomMode: configuredRooms.includes(lecture.roomName) ? lecture.roomName : 'custom',
        customRoom: configuredRooms.includes(lecture.roomName) ? '' : lecture.roomName,
      },
    ]);

    setIsDialogOpen(true);
  };

  // Handle saving one or multiple lecture slots
  const handleSaveLectures = async (keepOpenForNext: boolean = false) => {
    setValidationError(null);

    if (!modalBatch?.id) {
      toast.error('Batch information missing.');
      return;
    }

    if (formSlots.length === 0) {
      toast.error('No lectures configured.');
      return;
    }

    // 1. Validate each slot individually
    for (let i = 0; i < formSlots.length; i++) {
      const slot = formSlots[i];
      const slotLabel = formSlots.length > 1 ? `Lecture #${i + 1}` : 'Lecture';

      const startMin = timeToMinutes(slot.startTime);
      const endMin = timeToMinutes(slot.endTime);

      if (endMin <= startMin) {
        setValidationError(
          `${slotLabel}: End Time (${formatTime12h(slot.endTime)}) must be later than Start Time (${formatTime12h(slot.startTime)}).`
        );
        return;
      }

      if (!slot.subjectName.trim()) {
        setValidationError(`${slotLabel}: Please select a Subject.`);
        return;
      }

      const eligible = getTeachersForSubject(slot.subjectName, teachers);
      if (eligible.length === 0) {
        setValidationError(`${slotLabel}: No teacher is assigned to "${slot.subjectName}".`);
        return;
      }

      if (!slot.teacherId) {
        setValidationError(`${slotLabel}: Please select a Teacher.`);
        return;
      }

      // Check all additional assignments
      const assignedTeacherSet = new Set<string>([slot.teacherId]);
      for (let aIdx = 0; aIdx < slot.additionalAssignments.length; aIdx++) {
        const assign = slot.additionalAssignments[aIdx];
        const assignLabel = `Additional Teacher #${aIdx + 1}`;

        if (!assign.subjectName.trim()) {
          setValidationError(`${slotLabel}: Please select a Subject for ${assignLabel}.`);
          return;
        }

        if (!assign.teacherId) {
          setValidationError(`${slotLabel}: Please select a Teacher for ${assignLabel}.`);
          return;
        }

        if (assignedTeacherSet.has(assign.teacherId)) {
          const dupTeacher = teachers.find(t => t.id === assign.teacherId);
          setValidationError(
            `${slotLabel}: Teacher "${dupTeacher?.name || 'Selected teacher'}" cannot be assigned more than once to the same lecture slot.`
          );
          return;
        }
        assignedTeacherSet.add(assign.teacherId);
      }

      const finalRoom = slot.roomMode === 'custom' ? slot.customRoom.trim() : slot.roomMode;
      if (!finalRoom) {
        setValidationError(`${slotLabel}: Please specify a Classroom / Room.`);
        return;
      }
    }

    // 2. Validate internal overlaps between slots in the form
    for (let i = 0; i < formSlots.length; i++) {
      for (let j = i + 1; j < formSlots.length; j++) {
        const slotA = formSlots[i];
        const slotB = formSlots[j];

        const startA = timeToMinutes(slotA.startTime);
        const endA = timeToMinutes(slotA.endTime);
        const startB = timeToMinutes(slotB.startTime);
        const endB = timeToMinutes(slotB.endTime);

        // Same batch overlap check
        if (startA < endB && startB < endA) {
          setValidationError(
            `Time conflict: Lecture #${i + 1} (${formatTimeRange12h(slotA.startTime, slotA.endTime)}) overlaps with Lecture #${j + 1} (${formatTimeRange12h(slotB.startTime, slotB.endTime)}).`
          );
          return;
        }
      }
    }

    // 3. Validate against database lectures using validateTimetableLecture
    const currentLectures = [...timetableLectures];
    const candidateLecturesToSave: TimetableLecture[] = [];

    for (let i = 0; i < formSlots.length; i++) {
      const slot = formSlots[i];
      const primaryTeacher = teachers.find(t => t.id === slot.teacherId);

      const teacherIds: string[] = [slot.teacherId];
      const teacherNames: string[] = [primaryTeacher?.name || 'Teacher'];
      const teacherSubjectMap: Record<string, string> = {
        [slot.teacherId]: slot.subjectName,
      };

      const subjectNamesSet = new Set<string>([slot.subjectName]);

      for (const assign of slot.additionalAssignments) {
        if (assign.teacherId) {
          const t = teachers.find(item => item.id === assign.teacherId);
          teacherIds.push(assign.teacherId);
          teacherNames.push(t?.name || 'Teacher');
          teacherSubjectMap[assign.teacherId] = assign.subjectName;
          subjectNamesSet.add(assign.subjectName);
        }
      }

      const subjectNames = Array.from(subjectNamesSet);
      const finalSubjectName = subjectNames.join(' & ');

      const finalRoom = slot.roomMode === 'custom' ? slot.customRoom.trim() : slot.roomMode;
      const dayOrder = DAY_ORDER_MAP[modalDay] || 1;

      const candidate = {
        timetableId: editingLecture ? editingLecture.timetableId : undefined,
        academicYear: selectedAcademicYear,
        batchId: modalBatch.id,
        batchName: modalBatch.name,
        divisionId: selectedDivision !== 'All' ? selectedDivision : undefined,
        divisionName: selectedDivision !== 'All' ? selectedDivision : undefined,
        day: modalDay,
        dayOrder,
        startTime: slot.startTime,
        endTime: slot.endTime,
        subjectId: subjects.find(s => s.name === slot.subjectName)?.id,
        subjectName: finalSubjectName,
        subjectNames,
        teacherSubjectMap,
        teacherId: slot.teacherId,
        teacherName: primaryTeacher?.name || 'Teacher',
        teacherIds,
        teacherNames,
        roomId: finalRoom.toLowerCase().replace(/\s+/g, '_'),
        roomName: finalRoom,
        effectiveFrom: weekInfo.startDate,
        effectiveTo: weekInfo.endDate,
      };

      const validation = validateTimetableLecture(
        candidate,
        currentLectures,
        editingLecture?.timetableId
      );

      if (!validation.isValid) {
        const slotLabel = formSlots.length > 1 ? `Lecture #${i + 1}: ` : '';
        setValidationError(`${slotLabel}${validation.message}`);
        toast.error(`${slotLabel}${validation.message}`);
        return;
      }

      const finalId = editingLecture?.timetableId || `tt_${Date.now()}_${Math.random().toString(36).substring(2, 7)}`;
      const fullLecture: TimetableLecture = {
        ...candidate,
        timetableId: finalId,
        createdAt: editingLecture?.createdAt || new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      };

      candidateLecturesToSave.push(fullLecture);
      currentLectures.push(fullLecture);
    }

    if (isSavingLecture) return;
    setIsSavingLecture(true);

    try {
      for (const lec of candidateLecturesToSave) {
        if (editingLecture && lec.timetableId === editingLecture.timetableId) {
          await updateTimetableLecture(lec.timetableId, lec);
        } else {
          await addTimetableLecture(lec);
        }
      }

      if (editingLecture) {
        toast.success(`Lecture updated successfully for ${modalBatch.name}!`);
        setIsDialogOpen(false);
      } else {
        toast.success(
          `Successfully scheduled ${candidateLecturesToSave.length} lecture(s) for ${modalBatch.name} on ${modalDay}!`
        );

        if (keepOpenForNext) {
          const lastLec = candidateLecturesToSave[candidateLecturesToSave.length - 1];
          const nextStart = lastLec.endTime;
          const duration = Math.max(30, timeToMinutes(lastLec.endTime) - timeToMinutes(lastLec.startTime));
          const nextEnd = addMinutesToTime24(nextStart, duration);

          const defaultSubj = subjects[0]?.name || 'Mathematics';
          const eligible = getTeachersForSubject(defaultSubj, teachers);

          setFormSlots([
            {
              id: `slot_${Date.now()}`,
              startTime: nextStart,
              endTime: nextEnd,
              subjectName: defaultSubj,
              teacherId: eligible.length === 1 ? eligible[0].id : '',
              additionalAssignments: [],
              roomMode: lastLec.roomName || 'Room 1',
              customRoom: '',
            },
          ]);
          setValidationError(null);
          toast.info(`Configuring next lecture starting at ${formatTime12h(nextStart)}...`);
        } else {
          setIsDialogOpen(false);
        }
      }

      onDataChange();
    } catch (err) {
      console.error('Failed to save timetable lectures:', err);
      toast.error('Failed to save lectures. Please try again.');
    } finally {
      setIsSavingLecture(false);
    }
  };

  // Handle lecture deletion
  const handleDeleteLecture = async (timetableId: string, lectureName: string) => {
    try {
      const ok = await deleteTimetableLecture(timetableId);
      if (ok) {
        toast.success(`Lecture "${lectureName}" removed.`);
        onDataChange();
      } else {
        toast.error('Failed to delete lecture.');
      }
    } catch (err) {
      console.error('Delete lecture error:', err);
      toast.error('Error deleting lecture.');
    }
  };

  // Handle clear all lectures across entire timetable
  const handleClearAllLectures = async () => {
    if (timetableLectures.length === 0) {
      toast.info('No lectures to clear.');
      return;
    }
    setIsClearingAllLectures(true);
    try {
      const count = await clearAllTimetableLectures();
      toast.success(`Successfully cleared all ${count} scheduled lecture(s).`);
      onDataChange();
    } catch (err) {
      console.error('Clear all lectures error:', err);
      toast.error('Failed to clear lectures. Please try again.');
    } finally {
      setIsClearingAllLectures(false);
    }
  };

  // Handle clear all lectures for currently selected batch
  const handleClearBatchLectures = async () => {
    if (!selectedBatchId) return;
    const batchLecturesCount = timetableLectures.filter(l => l.batchId === selectedBatchId).length;
    if (batchLecturesCount === 0) {
      toast.info('No lectures to clear for this batch.');
      return;
    }
    setIsClearingAllLectures(true);
    try {
      const count = await clearAllTimetableLectures({ batchId: selectedBatchId });
      toast.success(`Cleared ${count} lecture(s) for ${selectedBatch?.name || 'batch'}.`);
      onDataChange();
    } catch (err) {
      console.error('Clear batch lectures error:', err);
      toast.error('Failed to clear batch lectures. Please try again.');
    } finally {
      setIsClearingAllLectures(false);
    }
  };

  // Navigate weeks
  const handlePrevWeek = () => {
    const prev = new Date(currentWeekDate);
    prev.setDate(prev.getDate() - 7);
    setCurrentWeekDate(prev);
  };

  const handleNextWeek = () => {
    const next = new Date(currentWeekDate);
    next.setDate(next.getDate() + 7);
    setCurrentWeekDate(next);
  };

  const handleCurrentWeek = () => {
    setCurrentWeekDate(new Date());
  };

  // Filter lectures for Single Batch View
  const singleBatchLectures = useMemo(() => {
    return timetableLectures.filter(l => {
      if (selectedBatchId && l.batchId !== selectedBatchId) return false;
      if (selectedDivision !== 'All' && l.divisionId && l.divisionId !== selectedDivision) return false;
      if (filterTeacherId !== 'all') {
        const ids = getLectureTeacherIds(l);
        if (!ids.includes(filterTeacherId)) return false;
      }
      if (filterSubject !== 'all' && l.subjectName.toLowerCase() !== filterSubject.toLowerCase()) return false;
      if (filterRoom !== 'all' && l.roomName.toLowerCase() !== filterRoom.toLowerCase()) return false;
      return true;
    });
  }, [
    timetableLectures,
    selectedBatchId,
    selectedDivision,
    filterTeacherId,
    filterSubject,
    filterRoom,
  ]);

  // Group lectures by day for Single Batch View
  const singleBatchByDay = useMemo(() => {
    const map: Record<string, TimetableLecture[]> = {
      Monday: [],
      Tuesday: [],
      Wednesday: [],
      Thursday: [],
      Friday: [],
      Saturday: [],
      Sunday: [],
    };
    singleBatchLectures.forEach(l => {
      if (map[l.day]) map[l.day].push(l);
    });
    Object.keys(map).forEach(day => {
      map[day].sort((a, b) => timeToMinutes(a.startTime) - timeToMinutes(b.startTime));
    });
    return map;
  }, [singleBatchLectures]);

  const activeDays = showSunday ? DAYS_OF_WEEK : DAYS_OF_WEEK.filter(d => d !== 'Sunday');

  // Next slot preview times for the + Add Another Lecture button
  const nextSlotStartTime = formSlots[formSlots.length - 1]?.endTime || '18:00';
  const lastSlotDuration = formSlots[formSlots.length - 1]
    ? Math.max(30, timeToMinutes(formSlots[formSlots.length - 1].endTime) - timeToMinutes(formSlots[formSlots.length - 1].startTime))
    : 120;
  const nextSlotEndTime = addMinutesToTime24(nextSlotStartTime, lastSlotDuration);

  return (
    <div className="space-y-6 animate-in fade-in duration-300">
      {/* ─────────────────────────────────────────────────────────────
          TOP CONTROL DECK: View Switcher, Academic Year, Effective Week, Tools
      ───────────────────────────────────────────────────────────── */}
      <Card className="p-5 sm:p-6 bg-card border-2 shadow-sm rounded-3xl space-y-5">
        <div className="flex flex-col lg:flex-row lg:items-center justify-between gap-4 border-b pb-5">
          <div>
            <div className="flex items-center gap-2">
              <span className="p-2.5 rounded-2xl bg-primary/10 text-primary">
                <Clock className="h-6 w-6" />
              </span>
              <div>
                <h2 className="text-xl sm:text-2xl font-black tracking-tight text-foreground">
                  Timetable Management
                </h2>
                <p className="text-xs text-muted-foreground mt-0.5">
                  Plan schedules across batches with multi-teacher/multi-subject support, sequential lectures, and conflict validation.
                </p>
              </div>
            </div>
          </div>

          {/* Action Tools: Templates, Duplicate, CSV Import, Sunday Toggle, Auto Generate */}
          <div className="flex flex-wrap items-center gap-2">
            <Button
              onClick={() => setAutoGenerateOpen(true)}
              size="sm"
              className="text-xs font-black rounded-xl gap-1.5 bg-gradient-to-r from-primary to-accent text-primary-foreground shadow-sm hover:opacity-95 transition-all"
            >
              <Sparkles className="h-3.5 w-3.5" /> Auto Generate Timetable
            </Button>
            <Button
              variant="outline"
              size="sm"
              onClick={() => setTemplateDialogOpen(true)}
              className="text-xs font-bold rounded-xl gap-1.5"
            >
              <Bookmark className="h-3.5 w-3.5 text-primary" /> Templates
            </Button>
            <Button
              variant="outline"
              size="sm"
              onClick={() => setDuplicateBatchOpen(true)}
              className="text-xs font-bold rounded-xl gap-1.5"
            >
              <Layers className="h-3.5 w-3.5 text-primary" /> Duplicate Batch
            </Button>
            <Button
              variant="outline"
              size="sm"
              onClick={() => setCsvImportDialogOpen(true)}
              className="text-xs font-bold rounded-xl gap-1.5"
            >
              <FileSpreadsheet className="h-3.5 w-3.5 text-primary" /> Import CSV
            </Button>
            <Button
              variant="outline"
              size="sm"
              onClick={() => setShowSunday(!showSunday)}
              className="text-xs font-bold rounded-xl"
            >
              {showSunday ? 'Hide Sunday' : '+ Show Sunday'}
            </Button>
            {timetableLectures.length > 0 && (
              <DeleteDialog
                title="Clear All Scheduled Lectures"
                description={`Are you sure you want to clear all ${timetableLectures.length} scheduled lectures across all batches? This will delete all lectures permanently from the database and cannot be undone.`}
                onDelete={handleClearAllLectures}
              >
                <Button
                  variant="outline"
                  size="sm"
                  disabled={isClearingAllLectures}
                  className="text-xs font-bold rounded-xl gap-1.5 text-destructive hover:bg-destructive/10 hover:text-destructive border-destructive/30"
                  title="Clear all lectures across all batches"
                >
                  <Trash2 className="h-3.5 w-3.5" />
                  {isClearingAllLectures ? 'Clearing...' : 'Clear All Lectures'}
                </Button>
              </DeleteDialog>
            )}
          </div>
        </div>

        {/* View Tabs & Selectors Row */}
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-4 items-end">
          {/* Main View Mode Selector (Tabs) */}
          <div className="lg:col-span-5 space-y-1.5">
            <Label className="text-xs font-black uppercase tracking-wider text-muted-foreground">
              Timetable View
            </Label>
            <div className="flex items-center p-1 rounded-2xl bg-muted/80 border text-xs font-extrabold">
              <button
                type="button"
                onClick={() => setActiveView('planner')}
                className={`flex-1 py-2 px-3 rounded-xl transition-all flex items-center justify-center gap-1.5 ${
                  activeView === 'planner'
                    ? 'bg-background shadow-xs text-primary'
                    : 'text-muted-foreground hover:text-foreground'
                }`}
              >
                <LayoutGrid className="h-4 w-4" />
                Planner Matrix
              </button>
              <button
                type="button"
                onClick={() => setActiveView('single_batch')}
                className={`flex-1 py-2 px-3 rounded-xl transition-all flex items-center justify-center gap-1.5 ${
                  activeView === 'single_batch'
                    ? 'bg-background shadow-xs text-primary'
                    : 'text-muted-foreground hover:text-foreground'
                }`}
              >
                <ListFilter className="h-4 w-4" />
                Batch Weekly View
              </button>
              <button
                type="button"
                onClick={() => setActiveView('printable')}
                className={`flex-1 py-2 px-3 rounded-xl transition-all flex items-center justify-center gap-1.5 ${
                  activeView === 'printable'
                    ? 'bg-background shadow-xs text-primary'
                    : 'text-muted-foreground hover:text-foreground'
                }`}
              >
                <Printer className="h-4 w-4" />
                Printable
              </button>
            </div>
          </div>

          {/* Academic Year Selector */}
          <div className="lg:col-span-3 space-y-1.5">
            <Label className="text-xs font-black uppercase tracking-wider text-muted-foreground">
              Academic Year
            </Label>
            <Select value={selectedAcademicYear} onValueChange={setSelectedAcademicYear}>
              <SelectTrigger className="h-11 rounded-2xl bg-background border-border/80 font-bold text-xs">
                <SelectValue placeholder="Academic Year" />
              </SelectTrigger>
              <SelectContent>
                {academicYears.map(yr => (
                  <SelectItem key={yr} value={yr} className="text-xs font-semibold">
                    {yr}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>

          {/* Effective Week Navigation */}
          <div className="lg:col-span-4 space-y-1.5">
            <div className="flex items-center justify-between">
              <Label className="text-xs font-black uppercase tracking-wider text-muted-foreground">
                Effective Week
              </Label>
              <button
                type="button"
                onClick={handleCurrentWeek}
                className="text-[10px] text-primary hover:underline font-bold"
              >
                Current Week
              </button>
            </div>
            <div className="flex items-center gap-1.5">
              <Button
                variant="outline"
                size="icon"
                onClick={handlePrevWeek}
                className="h-11 w-10 shrink-0 rounded-xl"
                title="Previous Week"
              >
                <ChevronLeft className="h-4 w-4" />
              </Button>
              <div className="flex-1 h-11 px-3 rounded-xl border border-border/80 bg-background flex items-center justify-center text-center text-xs font-extrabold text-foreground truncate">
                <Calendar className="h-3.5 w-3.5 mr-1.5 text-primary shrink-0" />
                <span className="truncate">{weekInfo.label}</span>
              </div>
              <Button
                variant="outline"
                size="icon"
                onClick={handleNextWeek}
                className="h-11 w-10 shrink-0 rounded-xl"
                title="Next Week"
              >
                <ChevronRight className="h-4 w-4" />
              </Button>
            </div>
          </div>
        </div>
      </Card>

      {/* ─────────────────────────────────────────────────────────────
          VIEW 1: BULK PLANNER MATRIX (Requirements 3 & 4)
      ───────────────────────────────────────────────────────────── */}
      {activeView === 'planner' && (
        <TimetablePlannerMatrix
          batches={batches}
          timetableLectures={timetableLectures}
          effectiveWeek={weekInfo}
          showSunday={showSunday}
          onAddLecture={(batch, day) => handleOpenAddLecture(batch, day)}
          onEditLecture={handleOpenEditLecture}
          onDeleteLecture={handleDeleteLecture}
        />
      )}

      {/* ─────────────────────────────────────────────────────────────
          VIEW 2: SINGLE BATCH WEEKLY VIEW (Requirements 17 & 18)
      ───────────────────────────────────────────────────────────── */}
      {activeView === 'single_batch' && (
        <div className="space-y-6">
          {/* Secondary Filter Bar for Batch View */}
          <Card className="p-4 sm:p-5 rounded-2xl border bg-card shadow-xs space-y-4">
            <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 pb-3 border-b">
              <div>
                <h3 className="font-black text-base text-foreground flex items-center gap-2">
                  <span>{selectedBatch?.name || 'Batch'} Timetable</span>
                  <Badge variant="outline" className="text-[11px] font-bold">
                    {timetableLectures.filter(l => l.batchId === selectedBatchId).length} scheduled
                  </Badge>
                </h3>
                <p className="text-xs text-muted-foreground">
                  View and manage weekly timetable specifically for this batch.
                </p>
              </div>
              {timetableLectures.some(l => l.batchId === selectedBatchId) && (
                <DeleteDialog
                  title={`Clear All Lectures for ${selectedBatch?.name || 'Batch'}`}
                  description={`Are you sure you want to clear all ${timetableLectures.filter(l => l.batchId === selectedBatchId).length} lecture(s) scheduled for ${selectedBatch?.name || 'this batch'}? This action cannot be undone.`}
                  onDelete={handleClearBatchLectures}
                >
                  <Button
                    variant="outline"
                    size="sm"
                    disabled={isClearingAllLectures}
                    className="text-xs font-bold rounded-xl gap-1.5 text-destructive hover:bg-destructive/10 hover:text-destructive border-destructive/30 self-start sm:self-auto"
                  >
                    <Trash2 className="h-3.5 w-3.5" />
                    {isClearingAllLectures ? 'Clearing...' : `Clear ${selectedBatch?.name || 'Batch'} Lectures`}
                  </Button>
                </DeleteDialog>
              )}
            </div>

            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-3">
              {/* Batch Selector */}
              <div className="space-y-1.5">
                <Label className="text-xs font-black uppercase tracking-wider text-muted-foreground">
                  Select Batch
                </Label>
                <Select value={selectedBatchId} onValueChange={setSelectedBatchId}>
                  <SelectTrigger className="h-10 rounded-xl font-bold text-xs text-primary">
                    <SelectValue placeholder="Select Batch" />
                  </SelectTrigger>
                  <SelectContent>
                    {batches.map(b => (
                      <SelectItem key={b.id} value={b.id} className="text-xs font-semibold">
                        {b.name} {b.year ? `(${b.year})` : ''}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>

              {/* Division */}
              <div className="space-y-1.5">
                <Label className="text-xs font-black uppercase tracking-wider text-muted-foreground">
                  Division
                </Label>
                <Select value={selectedDivision} onValueChange={setSelectedDivision}>
                  <SelectTrigger className="h-10 rounded-xl text-xs font-semibold">
                    <SelectValue placeholder="Division" />
                  </SelectTrigger>
                  <SelectContent>
                    {DEFAULT_DIVISIONS.map(div => (
                      <SelectItem key={div} value={div} className="text-xs font-semibold">
                        {div === 'All' ? 'All Divisions' : `Division ${div}`}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>

              {/* Teacher Filter */}
              <div className="space-y-1.5">
                <Label className="text-xs font-black uppercase tracking-wider text-muted-foreground">
                  Filter Teacher
                </Label>
                <Select value={filterTeacherId} onValueChange={setFilterTeacherId}>
                  <SelectTrigger className="h-10 rounded-xl text-xs font-semibold">
                    <SelectValue placeholder="All Teachers" />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="all">All Teachers</SelectItem>
                    {teachers.map(t => (
                      <SelectItem key={t.id} value={t.id} className="text-xs font-medium">
                        {t.name}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>

              {/* Subject Filter */}
              <div className="space-y-1.5">
                <Label className="text-xs font-black uppercase tracking-wider text-muted-foreground">
                  Filter Subject
                </Label>
                <Select value={filterSubject} onValueChange={setFilterSubject}>
                  <SelectTrigger className="h-10 rounded-xl text-xs font-semibold">
                    <SelectValue placeholder="All Subjects" />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="all">All Subjects</SelectItem>
                    {subjects.map(s => (
                      <SelectItem key={s.id} value={s.name} className="text-xs font-medium">
                        {s.name}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>
            </div>
          </Card>

          {/* Days Grid for Selected Batch */}
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-5">
            {activeDays.map(day => {
              const dayLectures = singleBatchByDay[day] || [];
              const dayDate = getDateForDayInWeek(day, weekInfo.startDate);

              return (
                <Card
                  key={day}
                  className="p-5 rounded-3xl border-2 bg-card hover:border-primary/40 transition-all shadow-xs flex flex-col justify-between"
                >
                  <div>
                    {/* Day Header */}
                    <div className="flex items-center justify-between pb-3 mb-3 border-b">
                      <div className="flex items-center gap-2.5">
                        <div className="h-9 w-9 rounded-xl bg-primary/10 text-primary flex items-center justify-center font-black text-xs">
                          {day.substring(0, 3).toUpperCase()}
                        </div>
                        <div>
                          <h4 className="font-black text-base text-foreground">{day}</h4>
                          <span className="text-[11px] text-muted-foreground font-semibold">
                            {dayDate} • {dayLectures.length} {dayLectures.length === 1 ? 'lecture' : 'lectures'}
                          </span>
                        </div>
                      </div>

                      {/* Copy Day Button */}
                      {dayLectures.length > 0 && selectedBatch && (
                        <Button
                          variant="ghost"
                          size="sm"
                          onClick={() => {
                            setCopyDaySource(day);
                            setCopyDayDialogOpen(true);
                          }}
                          className="h-8 px-2 text-[11px] font-bold text-muted-foreground hover:text-primary rounded-lg gap-1"
                          title={`Copy ${day} to other days`}
                        >
                          <Copy className="h-3 w-3" /> Copy
                        </Button>
                      )}
                    </div>

                    {/* Lectures List for this Day */}
                    {dayLectures.length === 0 ? (
                      <div className="py-8 text-center border border-dashed rounded-2xl bg-accent/5 my-2">
                        <Clock className="h-6 w-6 text-muted-foreground/30 mx-auto mb-1" />
                        <p className="text-xs text-muted-foreground font-semibold">
                          No lectures scheduled for {day}
                        </p>
                      </div>
                    ) : (
                      <div className="space-y-2.5 my-2">
                        {dayLectures.map(lecture => (
                          <div
                            key={lecture.timetableId}
                            className="p-3 rounded-2xl border bg-muted/20 hover:bg-muted/40 transition-all space-y-1.5 text-xs"
                          >
                            <div className="flex items-center justify-between">
                              <span className="inline-flex items-center gap-1 px-2 py-0.5 rounded-md bg-primary/10 text-primary font-black text-[11px]">
                                <Clock className="h-3 w-3" />
                                {formatTimeRange12h(lecture.startTime, lecture.endTime)}
                              </span>
                              <span className="inline-flex items-center gap-1 text-[11px] font-semibold text-muted-foreground">
                                <MapPin className="h-3 w-3 text-primary" />
                                {lecture.roomName || 'Room 1'}
                              </span>
                            </div>

                            <div className="font-black text-sm text-foreground">
                              {lecture.subjectName}
                            </div>

                            <div className="text-[11px] text-muted-foreground flex items-center gap-1">
                              <User className="h-3 w-3 text-primary shrink-0" />
                              <span className="font-semibold text-foreground truncate">
                                {formatLectureSubjectWithTeachers(lecture)}
                              </span>
                            </div>

                            <div className="flex items-center justify-end gap-1.5 pt-2 border-t border-border/50">
                              <Button
                                variant="ghost"
                                size="sm"
                                onClick={() => handleOpenEditLecture(lecture)}
                                className="h-7 px-2 text-xs font-bold text-primary hover:bg-primary/10 rounded-lg"
                              >
                                <Edit2 className="h-3 w-3 mr-1" /> Edit
                              </Button>
                              <DeleteDialog
                                title="Delete Lecture"
                                description={`Remove ${lecture.subjectName} from ${day}?`}
                                onDelete={() =>
                                  handleDeleteLecture(lecture.timetableId, lecture.subjectName)
                                }
                              />
                            </div>
                          </div>
                        ))}
                      </div>
                    )}
                  </div>

                  {/* + Add Lecture for this day */}
                  {selectedBatch && (
                    <Button
                      size="sm"
                      onClick={() => handleOpenAddLecture(selectedBatch, day)}
                      className="w-full mt-3 rounded-xl font-bold text-xs gap-1.5 bg-primary/10 text-primary hover:bg-primary hover:text-primary-foreground border border-primary/20 transition-all"
                    >
                      <Plus className="h-3.5 w-3.5" /> + Add Lecture
                    </Button>
                  )}
                </Card>
              );
            })}
          </div>
        </div>
      )}

      {/* ─────────────────────────────────────────────────────────────
          VIEW 3: PRINTABLE TIMETABLE (Requirement 37)
      ───────────────────────────────────────────────────────────── */}
      {activeView === 'printable' && (
        <TimetablePrintView
          batches={batches}
          timetableLectures={timetableLectures}
          effectiveWeek={weekInfo}
          academicYear={selectedAcademicYear}
          showSunday={showSunday}
        />
      )}

      {/* ─────────────────────────────────────────────────────────────
          MODAL: ADD / EDIT LECTURE
          - Shows "Add another subject" along with "Add another teacher"
          - Separate "+ Add Another Lecture" to chain multiple lectures (e.g. 4 to 6 PM, then 6 to 8 PM)
      ───────────────────────────────────────────────────────────── */}
      <Dialog open={isDialogOpen} onOpenChange={setIsDialogOpen}>
        <DialogContent className="sm:max-w-[620px] max-h-[92vh] overflow-y-auto rounded-3xl p-6">
          <DialogHeader>
            <DialogTitle className="text-xl font-black text-foreground flex items-center gap-2">
              <Calendar className="h-5 w-5 text-primary" />
              {editingLecture ? 'Edit Timetable Lecture' : 'Schedule Lecture(s)'}
            </DialogTitle>
            <DialogDescription className="text-xs text-muted-foreground">
              Academic Year: {selectedAcademicYear} • Week: {weekInfo.label}
            </DialogDescription>
          </DialogHeader>

          {/* Validation Error Banner */}
          {validationError && (
            <div className="p-3.5 rounded-2xl bg-destructive/10 border border-destructive/30 text-destructive text-xs font-semibold flex items-start gap-2 animate-in fade-in">
              <AlertTriangle className="h-4 w-4 shrink-0 mt-0.5" />
              <div>{validationError}</div>
            </div>
          )}

          <div className="space-y-5 pt-1">
            {/* Batch & Day Display (Read-Only) */}
            <div className="grid grid-cols-2 gap-3 p-3.5 rounded-2xl bg-muted/40 border">
              <div>
                <Label className="text-[10px] font-black uppercase tracking-wider text-muted-foreground block mb-1">
                  Batch / Class
                </Label>
                <div className="h-10 px-3 rounded-xl bg-background border flex items-center font-black text-sm text-primary truncate">
                  {modalBatch?.name || 'Class'}
                </div>
              </div>

              <div>
                <Label className="text-[10px] font-black uppercase tracking-wider text-muted-foreground block mb-1">
                  Day of Week
                </Label>
                <div className="h-10 px-3 rounded-xl bg-background border flex items-center font-extrabold text-sm text-foreground">
                  {modalDay}
                </div>
              </div>
            </div>

            {/* List of Lecture Slots being configured */}
            <div className="space-y-4">
              {formSlots.map((slot, index) => {
                const primaryEligible = getTeachersForSubject(slot.subjectName, teachers);

                return (
                  <Card
                    key={slot.id || index}
                    className="p-4 sm:p-5 rounded-3xl border-2 border-primary/20 bg-card shadow-xs space-y-4 relative"
                  >
                    {/* Slot Header if multiple slots */}
                    {formSlots.length > 1 && (
                      <div className="flex items-center justify-between pb-3 border-b">
                        <div className="flex items-center gap-2">
                          <Badge className="bg-primary text-primary-foreground font-black text-xs px-2.5 py-0.5 rounded-lg">
                            Lecture #{index + 1}
                          </Badge>
                          <span className="text-xs font-extrabold text-foreground">
                            {formatTimeRange12h(slot.startTime, slot.endTime)}
                          </span>
                        </div>
                        <Button
                          type="button"
                          variant="ghost"
                          size="icon"
                          onClick={() => handleRemoveSlot(index)}
                          className="h-8 w-8 text-destructive hover:bg-destructive/10 rounded-xl"
                          title="Remove this lecture slot"
                        >
                          <Trash2 className="h-4 w-4" />
                        </Button>
                      </div>
                    )}

                    {/* Time Configuration: Start & End Time */}
                    <div className="grid grid-cols-2 gap-3 p-3.5 rounded-2xl bg-muted/20 border">
                      <div className="space-y-1.5">
                        <Label className="text-[11px] font-black uppercase tracking-wider text-muted-foreground flex items-center gap-1">
                          <Clock className="h-3 w-3 text-primary" /> Start Time
                        </Label>
                        <Input
                          type="time"
                          value={slot.startTime}
                          onChange={e => updateSlot(index, { startTime: e.target.value })}
                          className="h-10 rounded-xl bg-background font-bold text-xs"
                          required
                        />
                        <span className="text-[10px] text-muted-foreground font-semibold">
                          {formatTime12h(slot.startTime)}
                        </span>
                      </div>

                      <div className="space-y-1.5">
                        <Label className="text-[11px] font-black uppercase tracking-wider text-muted-foreground flex items-center gap-1">
                          <Clock className="h-3 w-3 text-primary" /> End Time
                        </Label>
                        <Input
                          type="time"
                          value={slot.endTime}
                          onChange={e => updateSlot(index, { endTime: e.target.value })}
                          className="h-10 rounded-xl bg-background font-bold text-xs"
                          required
                        />
                        <span className="text-[10px] text-muted-foreground font-semibold">
                          {formatTime12h(slot.endTime)}
                        </span>
                      </div>
                    </div>

                    {/* Primary Subject & Primary Teacher */}
                    <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                      {/* Primary Subject */}
                      <div className="space-y-1.5">
                        <Label className="text-xs font-black uppercase tracking-wider text-muted-foreground">
                          Subject
                        </Label>
                        <Select
                          value={slot.subjectName}
                          onValueChange={val => handleSlotSubjectChange(index, val)}
                        >
                          <SelectTrigger className="h-11 rounded-xl font-bold text-xs">
                            <SelectValue placeholder="Select Subject" />
                          </SelectTrigger>
                          <SelectContent>
                            {subjects.map(s => (
                              <SelectItem key={s.id} value={s.name} className="font-semibold text-xs">
                                {s.name}
                              </SelectItem>
                            ))}
                            {subjects.length === 0 && (
                              <SelectItem value="Mathematics">Mathematics</SelectItem>
                            )}
                          </SelectContent>
                        </Select>
                      </div>

                      {/* Primary Teacher */}
                      <div className="space-y-1.5">
                        <div className="flex items-center justify-between">
                          <Label className="text-xs font-black uppercase tracking-wider text-muted-foreground">
                            Teacher
                          </Label>
                          {primaryEligible.length === 1 && (
                            <span className="text-[10px] font-bold text-emerald-600 flex items-center gap-0.5">
                              <CheckCircle2 className="h-2.5 w-2.5" /> 1 Assigned
                            </span>
                          )}
                        </div>

                        {primaryEligible.length === 0 ? (
                          <div className="p-2.5 rounded-xl bg-amber-500/10 border border-amber-500/30 text-amber-700 dark:text-amber-400 text-[11px] font-semibold">
                            No teacher assigned to {slot.subjectName}
                          </div>
                        ) : primaryEligible.length === 1 ? (
                          <div className="h-11 px-3 rounded-xl border border-emerald-500/40 bg-emerald-50/20 flex items-center justify-between text-xs">
                            <span className="font-black text-foreground truncate">{primaryEligible[0].name}</span>
                            <Badge className="bg-emerald-600 text-white font-bold text-[9px] px-1.5 py-0">Auto</Badge>
                          </div>
                        ) : (
                          <Select
                            value={slot.teacherId}
                            onValueChange={val => updateSlot(index, { teacherId: val })}
                          >
                            <SelectTrigger className="h-11 rounded-xl font-bold text-xs">
                              <SelectValue placeholder="Select Teacher" />
                            </SelectTrigger>
                            <SelectContent>
                              {primaryEligible.map(t => (
                                <SelectItem key={t.id} value={t.id} className="font-semibold text-xs">
                                  {t.name}
                                </SelectItem>
                              ))}
                            </SelectContent>
                          </Select>
                        )}
                      </div>
                    </div>

                    {/* ──────────────────────────────────────────────────
                        FEATURE: MULTI-TEACHER & MULTI-SUBJECT
                        "While adding another teacher, show add another subject"
                    ────────────────────────────────────────────────── */}
                    <div className="space-y-3 pt-1">
                      {/* List of Additional Teacher & Subject assignments */}
                      {slot.additionalAssignments.map((assign, aIdx) => {
                        const eligibleAssignTeachers = getEligibleAdditionalTeachers(
                          assign.subjectName,
                          slot,
                          aIdx
                        );
                        const isDifferentSubject =
                          assign.subjectName.toLowerCase() !== slot.subjectName.toLowerCase();

                        return (
                          <div
                            key={assign.id || aIdx}
                            className="p-3.5 rounded-2xl bg-primary/5 border border-primary/20 space-y-3 animate-in fade-in duration-150"
                          >
                            <div className="flex items-center justify-between">
                              <div className="flex items-center gap-1.5">
                                <Badge className="bg-primary/20 text-primary hover:bg-primary/20 font-black text-[10px] px-2 py-0.5 rounded-md">
                                  Teacher #{aIdx + 2}
                                </Badge>
                                <span className="text-xs font-black text-foreground">
                                  Additional Teacher & Subject
                                </span>
                              </div>
                              <Button
                                type="button"
                                variant="ghost"
                                size="sm"
                                onClick={() => handleRemoveAdditionalAssignment(index, aIdx)}
                                className="h-7 px-2 text-destructive hover:bg-destructive/10 text-xs font-bold rounded-lg"
                              >
                                <Trash2 className="h-3 w-3 mr-1" /> Remove
                              </Button>
                            </div>

                            <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                              {/* Additional Teacher */}
                              <div className="space-y-1.5">
                                <div className="flex items-center justify-between">
                                  <Label className="text-[11px] font-black uppercase tracking-wider text-muted-foreground flex items-center gap-1">
                                    <User className="h-3 w-3 text-primary" /> Additional Teacher
                                  </Label>
                                  {eligibleAssignTeachers.length === 1 && (
                                    <span className="text-[10px] font-bold text-emerald-600 flex items-center gap-0.5">
                                      <CheckCircle2 className="h-2.5 w-2.5" /> Auto-assigned
                                    </span>
                                  )}
                                </div>

                                {eligibleAssignTeachers.length === 0 ? (
                                  <div className="p-2 rounded-xl bg-amber-500/10 border border-amber-500/30 text-amber-700 dark:text-amber-400 text-[10px] font-semibold">
                                    No teacher assigned to {assign.subjectName}
                                  </div>
                                ) : eligibleAssignTeachers.length === 1 ? (
                                  <div className="h-10 px-3 rounded-xl border border-emerald-500/40 bg-emerald-50/20 flex items-center justify-between text-xs">
                                    <span className="font-black text-foreground truncate">
                                      {eligibleAssignTeachers[0].name}
                                    </span>
                                    <Badge className="bg-emerald-600 text-white font-bold text-[9px] px-1.5 py-0">
                                      Auto
                                    </Badge>
                                  </div>
                                ) : (
                                  <Select
                                    value={assign.teacherId}
                                    onValueChange={val =>
                                      handleUpdateAdditionalAssignment(index, aIdx, { teacherId: val })
                                    }
                                  >
                                    <SelectTrigger className="h-10 rounded-xl font-bold text-xs bg-background">
                                      <SelectValue placeholder="Select Teacher" />
                                    </SelectTrigger>
                                    <SelectContent>
                                      {eligibleAssignTeachers.map(t => (
                                        <SelectItem key={t.id} value={t.id} className="font-semibold text-xs">
                                          {t.name}
                                        </SelectItem>
                                      ))}
                                    </SelectContent>
                                  </Select>
                                )}
                              </div>

                              {/* Additional Subject - "Show Add Another Subject" */}
                              <div className="space-y-1.5">
                                <div className="flex items-center justify-between">
                                  <Label className="text-[11px] font-black uppercase tracking-wider text-muted-foreground flex items-center gap-1">
                                    <BookOpen className="h-3 w-3 text-primary" /> Subject (Add Another Subject)
                                  </Label>
                                  {isDifferentSubject ? (
                                    <span className="text-[10px] font-bold text-primary flex items-center gap-0.5">
                                      Different Subject
                                    </span>
                                  ) : (
                                    <span className="text-[10px] font-semibold text-muted-foreground">
                                      Same Subject
                                    </span>
                                  )}
                                </div>

                                <Select
                                  value={assign.subjectName}
                                  onValueChange={val =>
                                    handleUpdateAdditionalAssignment(index, aIdx, { subjectName: val })
                                  }
                                >
                                  <SelectTrigger className="h-10 rounded-xl font-bold text-xs bg-background">
                                    <SelectValue placeholder="Select Subject" />
                                  </SelectTrigger>
                                  <SelectContent>
                                    {subjects.map(s => (
                                      <SelectItem key={s.id} value={s.name} className="font-semibold text-xs">
                                        {s.name} {s.name === slot.subjectName ? '(Same Subject)' : ''}
                                      </SelectItem>
                                    ))}
                                  </SelectContent>
                                </Select>
                              </div>
                            </div>

                            {/* Summary chip */}
                            <div className="p-2 rounded-xl bg-background/80 border text-[11px] text-muted-foreground font-semibold flex items-center gap-2">
                              <Sparkles className="h-3.5 w-3.5 text-primary shrink-0" />
                              <span>
                                Teacher #{aIdx + 2}:{' '}
                                <strong className="text-foreground">
                                  {teachers.find(t => t.id === assign.teacherId)?.name || 'Select Teacher'}
                                </strong>{' '}
                                teaching{' '}
                                <strong className="text-foreground">{assign.subjectName}</strong>
                              </span>
                            </div>
                          </div>
                        );
                      })}

                      {/* Action buttons: + Add Another Teacher and + Add Another Subject */}
                      <div className="flex flex-wrap items-center gap-2 pt-1">
                        <Button
                          type="button"
                          variant="outline"
                          size="sm"
                          onClick={() => handleAddTeacherToSlot(index)}
                          className="h-8.5 px-3 rounded-xl border-dashed border-primary/50 bg-primary/5 hover:bg-primary/10 text-primary font-bold text-xs gap-1.5 transition-all"
                        >
                          <UserPlus className="h-3.5 w-3.5" /> + Add Another Teacher
                        </Button>

                        <Button
                          type="button"
                          variant="outline"
                          size="sm"
                          onClick={() => handleAddSubjectToSlot(index)}
                          className="h-8.5 px-3 rounded-xl border-dashed border-primary/50 bg-primary/5 hover:bg-primary/10 text-primary font-bold text-xs gap-1.5 transition-all"
                        >
                          <BookOpen className="h-3.5 w-3.5" /> + Add Another Subject
                        </Button>
                      </div>
                    </div>

                    {/* Classroom / Room */}
                    <div className="space-y-1.5">
                      <Label className="text-xs font-black uppercase tracking-wider text-muted-foreground">
                        Classroom / Room
                      </Label>
                      <div className="grid grid-cols-1 sm:grid-cols-2 gap-2">
                        <Select
                          value={slot.roomMode}
                          onValueChange={val => updateSlot(index, { roomMode: val })}
                        >
                          <SelectTrigger className="h-10 rounded-xl font-semibold text-xs">
                            <SelectValue placeholder="Select Room" />
                          </SelectTrigger>
                          <SelectContent>
                            {configuredRooms.map(r => (
                              <SelectItem key={r} value={r} className="text-xs font-semibold">
                                {r}
                              </SelectItem>
                            ))}
                            <SelectItem value="custom" className="text-xs font-semibold">
                              Custom Room / Other...
                            </SelectItem>
                          </SelectContent>
                        </Select>

                        {slot.roomMode === 'custom' && (
                          <Input
                            placeholder="e.g. Science Lab B, Hall 1"
                            value={slot.customRoom}
                            onChange={e => updateSlot(index, { customRoom: e.target.value })}
                            className="h-10 rounded-xl text-xs font-semibold"
                            required
                          />
                        )}
                      </div>
                    </div>
                  </Card>
                );
              })}
            </div>

            {/* ──────────────────────────────────────────────────
                FEATURE: ADD ANOTHER LECTURE (e.g. 4-6 PM, then 6-8 PM)
            ────────────────────────────────────────────────── */}
            {!editingLecture && (
              <Button
                type="button"
                variant="outline"
                onClick={handleAddSlot}
                className="w-full h-12 rounded-2xl border-2 border-dashed border-primary/40 text-primary hover:bg-primary/5 hover:border-primary font-black text-xs gap-2 transition-all shadow-xs"
              >
                <Plus className="h-4 w-4" />
                + Add Another Lecture (e.g. {formatTime12h(nextSlotStartTime)} – {formatTime12h(nextSlotEndTime)})
              </Button>
            )}
          </div>

          <DialogFooter className="pt-4 border-t flex flex-col sm:flex-row items-center justify-between gap-2">
            <Button
              type="button"
              variant="outline"
              onClick={() => setIsDialogOpen(false)}
              className="rounded-2xl font-bold text-xs w-full sm:w-auto"
            >
              Cancel
            </Button>

            <div className="flex items-center gap-2 w-full sm:w-auto justify-end">
              {!editingLecture && (
                <Button
                  type="button"
                  variant="secondary"
                  onClick={() => handleSaveLectures(true)}
                  disabled={isSavingLecture}
                  className="rounded-2xl font-bold text-xs w-full sm:w-auto"
                >
                  Save & Add Next
                </Button>
              )}

              <Button
                type="button"
                onClick={() => handleSaveLectures(false)}
                disabled={isSavingLecture}
                className="rounded-2xl font-black text-xs bg-primary text-primary-foreground hover:bg-primary/90 min-w-[130px] w-full sm:w-auto"
              >
                {isSavingLecture ? (
                  <span className="flex items-center gap-1.5">
                    <span className="h-3.5 w-3.5 border-2 border-primary-foreground border-t-transparent rounded-full animate-spin" />
                    Saving...
                  </span>
                ) : editingLecture ? (
                  'Update Lecture'
                ) : formSlots.length > 1 ? (
                  `Save ${formSlots.length} Lectures`
                ) : (
                  'Save Lecture'
                )}
              </Button>
            </div>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* ─────────────────────────────────────────────────────────────
          SUB-MODALS: COPY DAY, DUPLICATE BATCH, TEMPLATES, CSV IMPORT
      ───────────────────────────────────────────────────────────── */}
      {selectedBatch && (
        <TimetableCopyDayDialog
          open={copyDayDialogOpen}
          onOpenChange={setCopyDayDialogOpen}
          sourceBatch={selectedBatch}
          sourceDay={copyDaySource}
          effectiveWeek={weekInfo}
          allLectures={timetableLectures}
          showSunday={showSunday}
          onSuccess={onDataChange}
        />
      )}

      {selectedBatch && (
        <TimetableDuplicateBatchDialog
          open={duplicateBatchOpen}
          onOpenChange={setDuplicateBatchOpen}
          sourceBatch={selectedBatch}
          batches={batches}
          effectiveWeek={weekInfo}
          allLectures={timetableLectures}
          showSunday={showSunday}
          onSuccess={onDataChange}
        />
      )}

      {selectedBatch && (
        <TimetableTemplateDialog
          open={templateDialogOpen}
          onOpenChange={setTemplateDialogOpen}
          currentBatch={selectedBatch}
          effectiveWeek={weekInfo}
          academicYear={selectedAcademicYear}
          allLectures={timetableLectures}
          onSuccess={onDataChange}
        />
      )}

      <TimetableCsvImportDialog
        open={csvImportDialogOpen}
        onOpenChange={setCsvImportDialogOpen}
        batches={batches}
        subjects={subjects}
        teachers={teachers}
        effectiveWeek={weekInfo}
        academicYear={selectedAcademicYear}
        allLectures={timetableLectures}
        onSuccess={onDataChange}
      />

      <TimetableAutoGenerateDialog
        open={autoGenerateOpen}
        onOpenChange={setAutoGenerateOpen}
        batches={batches}
        subjects={subjects}
        teachers={teachers}
        effectiveWeek={weekInfo}
        academicYear={selectedAcademicYear}
        academicYears={academicYears}
        onSuccess={onDataChange}
      />
    </div>
  );
};

export default AdminTimetableBuilder;
