import { useState, useEffect, useMemo } from 'react';
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
  DialogFooter,
} from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Checkbox } from '@/components/ui/checkbox';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import { Badge } from '@/components/ui/badge';
import {
  Sparkles,
  Calendar,
  Clock,
  Users,
  BookOpen,
  MapPin,
  CheckCircle2,
  AlertTriangle,
  AlertCircle,
  ArrowRight,
  ArrowLeft,
  RotateCcw,
  Wand2,
  Trash2,
  Edit2,
  Plus,
  Layers,
  ChevronDown,
  ChevronUp,
  Info,
  Check,
} from 'lucide-react';
import { toast } from 'sonner';
import {
  Batch,
  Subject,
  Teacher,
  TimetableLecture,
  addTimetableLecturesBulk,
  formatTimeRange12h,
  formatTime12h,
  timeToMinutes,
  getLectureTeacherIds,
  getLectureTeacherNames,
  getRooms,
  getBatchTimings,
  formatLectureSubjectWithTeachers,
  DAY_ORDER_MAP,
} from '@/lib/localStorage';
import { WeekInfo, parseLocalDate, toLocalDateString } from '@/lib/timetableUtils';
import {
  AutoGenerateConfig,
  BatchScheduleConfig,
  BatchSubjectConfig,
  GeneratorResult,
  generateAutoTimetable,
  validateGeneratedTimetable,
  autoFixTimetable,
  findEligibleTeachers,
  minutesToTime,
} from '@/lib/timetableGenerator';

interface TimetableAutoGenerateDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  batches: Batch[];
  subjects: Subject[];
  teachers: Teacher[];
  effectiveWeek: WeekInfo;
  academicYear: string;
  academicYears: string[];
  onSuccess: () => void;
}

const ALL_WEEK_DAYS = [
  'Monday',
  'Tuesday',
  'Wednesday',
  'Thursday',
  'Friday',
  'Saturday',
  'Sunday',
];

const LECTURE_DURATION_OPTIONS = [
  { label: '30 min', value: 30 },
  { label: '45 min', value: 45 },
  { label: '1 hour', value: 60 },
  { label: '1.5 hours', value: 90 },
  { label: '2 hours', value: 120 },
  { label: '2.5 hours', value: 150 },
  { label: '3 hours', value: 180 },
];

const GAP_OPTIONS = [
  { label: 'No Gap', value: 0 },
  { label: '15 minutes', value: 15 },
  { label: '30 minutes', value: 30 },
  { label: '45 minutes', value: 45 },
  { label: '1 hour', value: 60 },
];

const GENERATION_STEPS = [
  { id: 'batches', label: 'Loading batches' },
  { id: 'subjects', label: 'Loading subjects' },
  { id: 'teachers', label: 'Checking teachers' },
  { id: 'rooms', label: 'Checking rooms' },
  { id: 'slots', label: 'Generating time slots' },
  { id: 'assigning', label: 'Assigning lectures...' },
  { id: 'conflicts', label: 'Checking conflicts...' },
  { id: 'optimizing', label: 'Optimizing timetable...' },
];

export const TimetableAutoGenerateDialog = ({
  open,
  onOpenChange,
  batches,
  subjects,
  teachers,
  effectiveWeek,
  academicYear,
  academicYears,
  onSuccess,
}: TimetableAutoGenerateDialogProps) => {
  // Step indicator: 1 = Week & Time, 2 = Batches, 3 = Subjects, 4 = Generate, 5 = Review
  const [currentStep, setCurrentStep] = useState<1 | 2 | 3 | 4 | 5>(1);

  // STEP 1 STATE: Week & Time
  const [selectedAcademicYear, setSelectedAcademicYear] = useState<string>(academicYear || '2026-27');
  const [weekStart, setWeekStart] = useState<string>(effectiveWeek.startDate || toLocalDateString(new Date()));
  const [workingDays, setWorkingDays] = useState<string[]>([
    'Monday',
    'Tuesday',
    'Wednesday',
    'Thursday',
    'Friday',
    'Saturday',
  ]);
  const [instituteStartTime, setInstituteStartTime] = useState<string>('15:00'); // 3:00 PM
  const [instituteEndTime, setInstituteEndTime] = useState<string>('21:00');   // 9:00 PM
  const [defaultDuration, setDefaultDuration] = useState<number>(120);         // 2 hours
  const [gapMinutes, setGapMinutes] = useState<number>(30);                    // 30 min

  // STEP 2 & 3 STATE: Batch & Subject Configuration
  const [batchConfigs, setBatchConfigs] = useState<Record<string, BatchScheduleConfig>>({});
  const [activeSubjectBatchId, setActiveSubjectBatchId] = useState<string>('');

  // STEP 4 STATE: Generation Animation
  const [generationStepIndex, setGenerationStepIndex] = useState<number>(0);

  // STEP 5 STATE: Review, Editing, Validation
  const [generatedResult, setGeneratedResult] = useState<GeneratorResult | null>(null);
  const [previewDayFilter, setPreviewDayFilter] = useState<string>('all');
  const [previewBatchFilter, setPreviewBatchFilter] = useState<string>('all');
  const [editingLecture, setEditingLecture] = useState<TimetableLecture | null>(null);
  const [isManualAddOpen, setIsManualAddOpen] = useState<boolean>(false);
  const [isSavingToDb, setIsSavingToDb] = useState<boolean>(false);

  // Manual lecture edit/add form states
  const [editDay, setEditDay] = useState<string>('Monday');
  const [editStartTime, setEditStartTime] = useState<string>('16:00');
  const [editEndTime, setEditEndTime] = useState<string>('18:00');
  const [editSubjectName, setEditSubjectName] = useState<string>('');
  const [editTeacher1Id, setEditTeacher1Id] = useState<string>('');
  const [editTeacher2Id, setEditTeacher2Id] = useState<string>('');
  const [editRoomName, setEditRoomName] = useState<string>('Room 1');
  const [editBatchId, setEditBatchId] = useState<string>('');

  const [editSubject2Name, setEditSubject2Name] = useState<string>('');

  // Available Rooms
  const availableRooms = useMemo(() => {
    const list = getRooms();
    return list.length > 0 ? list : ['Room 1', 'Room 2', 'Room 3', 'Room 4', 'Room 5'];
  }, []);

  // Calculate Week End automatically based on weekStart + 6 days
  const calculatedWeekEnd = useMemo(() => {
    if (!weekStart) return '';
    try {
      const start = parseLocalDate(weekStart);
      const end = new Date(start);
      end.setDate(end.getDate() + 6);
      return toLocalDateString(end);
    } catch {
      return '';
    }
  }, [weekStart]);

  // Initialize or reset configurations when opening dialog - automatically fetches from Institute Settings
  useEffect(() => {
    if (open) {
      setCurrentStep(1);
      setSelectedAcademicYear(academicYear || '2026-27');
      setWeekStart(effectiveWeek.startDate || toLocalDateString(new Date()));

      // Automatically fetch configured batch timings, default lectures, and combined batch flags from Settings
      const savedBatchTimings = getBatchTimings();

      const initialConfigs: Record<string, BatchScheduleConfig> = {};
      batches.forEach(b => {
        const saved = savedBatchTimings[b.id];
        const preferredStart = saved?.startTime || '16:00';
        const preferredEnd = saved?.endTime || '20:00';
        const defaultLecs = saved?.defaultLecturesPerWeek || 2;
        const isCombined =
          typeof saved?.isCombinedBatch === 'boolean'
            ? saved.isCombinedBatch
            : (b.name.toLowerCase().includes('&') || b.name.toLowerCase().includes('and'));

        const subjectMap: Record<string, BatchSubjectConfig> = {};
        subjects.forEach(s => {
          subjectMap[s.name] = {
            subjectName: s.name,
            selected: true,
            lecturesPerWeek: defaultLecs, // automatically fetched from Settings
            assignTwoTeachers: isCombined,
          };
        });

        initialConfigs[b.id] = {
          batchId: b.id,
          batchName: b.name,
          selected: true,
          preferredStartTime: preferredStart,
          preferredEndTime: preferredEnd,
          defaultLecturesPerWeek: defaultLecs,
          isCombinedBatch: isCombined,
          subjectConfigs: subjectMap,
        };
      });

      setBatchConfigs(initialConfigs);
      if (batches.length > 0) {
        setActiveSubjectBatchId(batches[0].id);
      }
      setGeneratedResult(null);
    }
  }, [open, batches, subjects, academicYear, effectiveWeek.startDate]);

  // Working day toggler
  const toggleWorkingDay = (day: string) => {
    setWorkingDays(prev => {
      if (prev.includes(day)) {
        if (prev.length <= 1) {
          toast.error('At least one working day must be selected.');
          return prev;
        }
        return prev.filter(d => d !== day);
      } else {
        return [...prev, day];
      }
    });
  };

  // Batch selection toggle
  const toggleBatchSelected = (batchId: string) => {
    setBatchConfigs(prev => {
      const current = prev[batchId];
      if (!current) return prev;
      return {
        ...prev,
        [batchId]: {
          ...current,
          selected: !current.selected,
        },
      };
    });
  };

  // Toggle all batches
  const toggleAllBatches = (select: boolean) => {
    setBatchConfigs(prev => {
      const next = { ...prev };
      Object.keys(next).forEach(id => {
        next[id] = { ...next[id], selected: select };
      });
      return next;
    });
  };

  // Update batch schedule times
  const updateBatchScheduleTimes = (
    batchId: string,
    field: 'preferredStartTime' | 'preferredEndTime',
    val: string
  ) => {
    setBatchConfigs(prev => {
      const current = prev[batchId];
      if (!current) return prev;
      return {
        ...prev,
        [batchId]: {
          ...current,
          [field]: val,
        },
      };
    });
  };

  // Update subject configuration for a batch
  const updateSubjectConfig = (
    batchId: string,
    subjectName: string,
    updates: Partial<BatchSubjectConfig>
  ) => {
    setBatchConfigs(prev => {
      const bCfg = prev[batchId];
      if (!bCfg) return prev;
      const sCfg = bCfg.subjectConfigs[subjectName] || {
        subjectName,
        selected: true,
        lecturesPerWeek: 2,
        assignTwoTeachers: false,
      };
      return {
        ...prev,
        [batchId]: {
          ...bCfg,
          subjectConfigs: {
            ...bCfg.subjectConfigs,
            [subjectName]: {
              ...sCfg,
              ...updates,
            },
          },
        },
      };
    });
  };

  // Selected batches list
  const selectedBatchesList = useMemo(() => {
    return Object.values(batchConfigs).filter(b => b.selected);
  }, [batchConfigs]);

  // Execute Generation
  const handleStartGeneration = () => {
    if (selectedBatchesList.length === 0) {
      toast.error('Please select at least one batch to schedule.');
      setCurrentStep(2);
      return;
    }

    // Verify at least one subject is selected
    const totalSelectedSubjects = selectedBatchesList.reduce((acc, b) => {
      return acc + Object.values(b.subjectConfigs).filter(s => s.selected).length;
    }, 0);

    if (totalSelectedSubjects === 0) {
      toast.error('Please select at least one subject to schedule across your batches.');
      setCurrentStep(3);
      return;
    }

    // Switch to step 4 (Generate Animation)
    setCurrentStep(4);
    setGenerationStepIndex(0);

    const fullConfig: AutoGenerateConfig = {
      academicYear: selectedAcademicYear,
      weekStart,
      weekEnd: calculatedWeekEnd,
      workingDays,
      instituteStartTime,
      instituteEndTime,
      defaultDuration,
      gapMinutes,
      batchConfigs,
    };

    // Animate visual steps progressively over ~1.4s
    const stepDuration = 180;
    GENERATION_STEPS.forEach((_, idx) => {
      setTimeout(() => {
        setGenerationStepIndex(idx);
      }, idx * stepDuration);
    });

    setTimeout(() => {
      // Run deterministic algorithm
      const result = generateAutoTimetable(fullConfig, teachers, availableRooms);
      setGeneratedResult(result);
      setCurrentStep(5);

      if (result.validation.isValid && result.unscheduled.length === 0) {
        toast.success(`Timetable generated successfully with 0 conflicts! (${result.lectures.length} lectures scheduled)`);
      } else if (result.unscheduled.length > 0) {
        toast.warning(`${result.unscheduled.length} lecture(s) could not find a conflict-free slot. Please review below.`);
      }
    }, GENERATION_STEPS.length * stepDuration + 200);
  };

  // Regenerate with same configuration
  const handleRegenerate = () => {
    handleStartGeneration();
  };

  // Auto-Fix Trigger
  const handleAutoFix = () => {
    if (!generatedResult) return;
    const fullConfig: AutoGenerateConfig = {
      academicYear: selectedAcademicYear,
      weekStart,
      weekEnd: calculatedWeekEnd,
      workingDays,
      instituteStartTime,
      instituteEndTime,
      defaultDuration,
      gapMinutes,
      batchConfigs,
    };

    const fixed = autoFixTimetable(
      generatedResult.lectures,
      fullConfig,
      teachers,
      availableRooms
    );

    setGeneratedResult(prev => {
      if (!prev) return null;
      return {
        ...prev,
        lectures: fixed.lectures,
        validation: fixed.validation,
        stats: {
          ...prev.stats,
          conflictsCount: fixed.validation.totalConflicts,
        },
      };
    });

    if (fixed.validation.isValid) {
      toast.success(`Successfully resolved all conflicts automatically! (${fixed.fixedCount} modifications made)`);
    } else {
      toast.info(`Auto-fix made ${fixed.fixedCount} adjustments. ${fixed.validation.totalConflicts} issue(s) remaining.`);
    }
  };

  // Delete lecture in review preview
  const handleDeletePreviewLecture = (timetableId: string) => {
    if (!generatedResult) return;
    const updated = generatedResult.lectures.filter(l => l.timetableId !== timetableId);
    const fullConfig: AutoGenerateConfig = {
      academicYear: selectedAcademicYear,
      weekStart,
      weekEnd: calculatedWeekEnd,
      workingDays,
      instituteStartTime,
      instituteEndTime,
      defaultDuration,
      gapMinutes,
      batchConfigs,
    };
    const validation = validateGeneratedTimetable(updated, fullConfig, teachers);

    setGeneratedResult({
      ...generatedResult,
      lectures: updated,
      validation,
      stats: {
        ...generatedResult.stats,
        lecturesCount: updated.length,
        conflictsCount: validation.totalConflicts,
      },
    });
    toast.info('Lecture removed from preview.');
  };

  // Open Edit modal for a lecture
  const handleOpenEditLecture = (lec: TimetableLecture) => {
    setEditingLecture(lec);
    setEditDay(lec.day);
    setEditStartTime(lec.startTime);
    setEditEndTime(lec.endTime);
    const subjs = lec.subjectNames && lec.subjectNames.length > 0 ? lec.subjectNames : [lec.subjectName];
    setEditSubjectName(subjs[0] || lec.subjectName);
    setEditSubject2Name(subjs[1] || '');
    const tIds = getLectureTeacherIds(lec);
    setEditTeacher1Id(tIds[0] || '');
    setEditTeacher2Id(tIds[1] || '');
    setEditRoomName(lec.roomName || availableRooms[0] || 'Room 1');
    setEditBatchId(lec.batchId);
  };

  // Save edited lecture
  const handleSaveEditedLecture = () => {
    if (!generatedResult || !editingLecture) return;

    if (timeToMinutes(editEndTime) <= timeToMinutes(editStartTime)) {
      toast.error('End Time must be later than Start Time.');
      return;
    }
    if (!editSubjectName) {
      toast.error('Please select a Subject.');
      return;
    }
    if (!editTeacher1Id) {
      toast.error('Please select at least one Teacher.');
      return;
    }

    const t1 = teachers.find(t => t.id === editTeacher1Id);
    const t2 = editTeacher2Id ? teachers.find(t => t.id === editTeacher2Id) : null;

    const teacherIds = t2 ? [t1!.id, t2.id] : [t1!.id];
    const teacherNames = t2 ? [t1!.name, t2.name] : [t1!.name];

    const subjectNames = editSubject2Name && t2
      ? [editSubjectName, editSubject2Name]
      : [editSubjectName];

    const finalSubjectName = subjectNames.join(' & ');

    const teacherSubjectMap: Record<string, string> = {
      [t1!.id]: editSubjectName,
    };
    if (t2) {
      teacherSubjectMap[t2.id] = editSubject2Name || editSubjectName;
    }

    const updatedLectures = generatedResult.lectures.map(l => {
      if (l.timetableId === editingLecture.timetableId) {
        return {
          ...l,
          day: editDay,
          dayOrder: DAY_ORDER_MAP[editDay] || 1,
          startTime: editStartTime,
          endTime: editEndTime,
          subjectName: finalSubjectName,
          subjectNames,
          teacherSubjectMap,
          teacherId: teacherIds[0],
          teacherName: teacherNames[0],
          teacherIds,
          teacherNames,
          roomName: editRoomName,
          updatedAt: new Date().toISOString(),
        };
      }
      return l;
    });

    const fullConfig: AutoGenerateConfig = {
      academicYear: selectedAcademicYear,
      weekStart,
      weekEnd: calculatedWeekEnd,
      workingDays,
      instituteStartTime,
      instituteEndTime,
      defaultDuration,
      gapMinutes,
      batchConfigs,
    };
    const validation = validateGeneratedTimetable(updatedLectures, fullConfig, teachers);

    setGeneratedResult({
      ...generatedResult,
      lectures: updatedLectures,
      validation,
      stats: {
        ...generatedResult.stats,
        conflictsCount: validation.totalConflicts,
      },
    });

    setEditingLecture(null);
    toast.success('Lecture updated in preview!');
  };

  // Save manually added lecture
  const handleSaveManualLecture = () => {
    if (!generatedResult) return;
    const targetBatch = batches.find(b => b.id === editBatchId) || selectedBatchesList[0];
    if (!targetBatch) {
      toast.error('Please select a Batch.');
      return;
    }
    if (timeToMinutes(editEndTime) <= timeToMinutes(editStartTime)) {
      toast.error('End Time must be later than Start Time.');
      return;
    }
    if (!editSubjectName) {
      toast.error('Please select a Subject.');
      return;
    }
    if (!editTeacher1Id) {
      toast.error('Please select a Teacher.');
      return;
    }

    const t1 = teachers.find(t => t.id === editTeacher1Id);
    const t2 = editTeacher2Id ? teachers.find(t => t.id === editTeacher2Id) : null;
    const teacherIds = t2 ? [t1!.id, t2.id] : [t1!.id];
    const teacherNames = t2 ? [t1!.name, t2.name] : [t1!.name];

    const subjectNames = editSubject2Name && t2
      ? [editSubjectName, editSubject2Name]
      : [editSubjectName];

    const finalSubjectName = subjectNames.join(' & ');

    const teacherSubjectMap: Record<string, string> = {
      [t1!.id]: editSubjectName,
    };
    if (t2) {
      teacherSubjectMap[t2.id] = editSubject2Name || editSubjectName;
    }

    const newLec: TimetableLecture = {
      timetableId: `lec_manual_${Date.now()}_${Math.random().toString(36).substring(2, 6)}`,
      academicYear: selectedAcademicYear,
      batchId: targetBatch.id,
      batchName: targetBatch.name,
      day: editDay,
      dayOrder: DAY_ORDER_MAP[editDay] || 1,
      startTime: editStartTime,
      endTime: editEndTime,
      subjectName: finalSubjectName,
      subjectNames,
      teacherSubjectMap,
      teacherId: teacherIds[0],
      teacherName: teacherNames[0],
      teacherIds,
      teacherNames,
      roomName: editRoomName || availableRooms[0] || 'Room 1',
      effectiveFrom: weekStart,
      effectiveTo: calculatedWeekEnd,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    };

    const updatedLectures = [...generatedResult.lectures, newLec];
    const fullConfig: AutoGenerateConfig = {
      academicYear: selectedAcademicYear,
      weekStart,
      weekEnd: calculatedWeekEnd,
      workingDays,
      instituteStartTime,
      instituteEndTime,
      defaultDuration,
      gapMinutes,
      batchConfigs,
    };
    const validation = validateGeneratedTimetable(updatedLectures, fullConfig, teachers);

    setGeneratedResult({
      ...generatedResult,
      lectures: updatedLectures,
      validation,
      stats: {
        ...generatedResult.stats,
        lecturesCount: updatedLectures.length,
        conflictsCount: validation.totalConflicts,
      },
    });

    setIsManualAddOpen(false);
    toast.success('Lecture added to preview!');
  };

  // Final Commit to Storage & Firebase
  const handleSaveToDatabase = async () => {
    if (!generatedResult) return;

    if (!generatedResult.validation.isValid) {
      toast.error('Cannot save timetable with active conflicts. Please resolve all conflicts or click Fix Automatically.');
      return;
    }

    if (generatedResult.lectures.length === 0) {
      toast.error('No lectures generated to save.');
      return;
    }

    setIsSavingToDb(true);
    try {
      await addTimetableLecturesBulk(generatedResult.lectures);
      toast.success(
        `✨ Success! Saved ${generatedResult.lectures.length} lectures across ${generatedResult.stats.batchesCount} batches for week ${effectiveWeek.label || weekStart}!`
      );
      onSuccess();
      onOpenChange(false);
    } catch (err) {
      console.error('Save generated timetable error:', err);
      toast.error('Failed to save generated timetable. Please try again.');
    } finally {
      setIsSavingToDb(false);
    }
  };

  // Filtered preview lectures
  const filteredPreviewLectures = useMemo(() => {
    if (!generatedResult) return [];
    return generatedResult.lectures.filter(l => {
      if (previewDayFilter !== 'all' && l.day.toLowerCase() !== previewDayFilter.toLowerCase()) return false;
      if (previewBatchFilter !== 'all' && l.batchId !== previewBatchFilter) return false;
      return true;
    });
  }, [generatedResult, previewDayFilter, previewBatchFilter]);

  // Group filtered lectures by Day then Batch for structured preview
  const groupedPreview = useMemo(() => {
    const map: Record<string, Record<string, TimetableLecture[]>> = {};

    workingDays.forEach(day => {
      map[day] = {};
    });

    filteredPreviewLectures.forEach(l => {
      if (!map[l.day]) map[l.day] = {};
      if (!map[l.day][l.batchName]) map[l.day][l.batchName] = [];
      map[l.day][l.batchName].push(l);
    });

    // Sort lectures by start time
    Object.keys(map).forEach(day => {
      Object.keys(map[day]).forEach(bName => {
        map[day][bName].sort((a, b) => timeToMinutes(a.startTime) - timeToMinutes(b.startTime));
      });
    });

    return map;
  }, [filteredPreviewLectures, workingDays]);

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent
        className="max-w-4xl w-full h-[100dvh] sm:h-auto sm:max-h-[92vh] overflow-y-auto sm:rounded-3xl p-0 flex flex-col border-2 shadow-2xl bg-card"
      >
        {/* Modal Header */}
        <div className="p-5 sm:p-6 border-b bg-muted/40 sticky top-0 z-20 backdrop-blur-md">
          <div className="flex items-center justify-between gap-4">
            <div className="flex items-center gap-3">
              <span className="p-2.5 rounded-2xl bg-primary text-primary-foreground shadow-sm shadow-primary/30">
                <Sparkles className="h-6 w-6" />
              </span>
              <div>
                <DialogTitle className="text-xl sm:text-2xl font-black tracking-tight text-foreground flex items-center gap-2">
                  Auto Generate Timetable
                  <Badge variant="outline" className="text-[10px] uppercase font-bold tracking-wider text-primary border-primary/40 bg-primary/5">
                    Deterministic AI Scheduler
                  </Badge>
                </DialogTitle>
                <DialogDescription className="text-xs text-muted-foreground mt-0.5 max-w-xl">
                  Automatically create a weekly timetable based on your batches, subjects, teachers, rooms and available time slots.
                </DialogDescription>
              </div>
            </div>
          </div>

          {/* Multi-Step Wizard Indicator */}
          <div className="grid grid-cols-5 gap-2 mt-5">
            {[
              { num: 1, label: 'Week & Time' },
              { num: 2, label: 'Batches' },
              { num: 3, label: 'Subjects' },
              { num: 4, label: 'Generate' },
              { num: 5, label: 'Review' },
            ].map(step => {
              const isActive = currentStep === step.num;
              const isPassed = currentStep > step.num;

              return (
                <div
                  key={step.num}
                  className={`flex flex-col items-center sm:items-start p-2 rounded-xl transition-all border ${
                    isActive
                      ? 'bg-primary/10 border-primary text-primary font-black shadow-xs'
                      : isPassed
                      ? 'bg-muted/70 border-muted text-foreground font-bold'
                      : 'border-transparent text-muted-foreground opacity-60'
                  }`}
                >
                  <div className="flex items-center gap-1.5 text-xs">
                    <span
                      className={`h-5 w-5 rounded-full flex items-center justify-center text-[10px] font-black shrink-0 ${
                        isActive
                          ? 'bg-primary text-primary-foreground'
                          : isPassed
                          ? 'bg-emerald-600 text-white'
                          : 'bg-muted text-muted-foreground'
                      }`}
                    >
                      {isPassed ? <Check className="h-3 w-3" /> : step.num}
                    </span>
                    <span className="hidden sm:inline truncate">{step.label}</span>
                  </div>
                </div>
              );
            })}
          </div>
        </div>

        {/* Modal Body / Steps */}
        <div className="p-5 sm:p-6 flex-1 overflow-y-auto space-y-6">
          {/* ══════════════════════════════════════════════════════════
              STEP 1: WEEK & TIME
          ══════════════════════════════════════════════════════════ */}
          {currentStep === 1 && (
            <div className="space-y-6 animate-in fade-in-50 duration-200">
              <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
                <div className="space-y-1.5">
                  <Label className="text-xs font-black uppercase tracking-wider text-muted-foreground">
                    Academic Year
                  </Label>
                  <Select value={selectedAcademicYear} onValueChange={setSelectedAcademicYear}>
                    <SelectTrigger className="h-11 rounded-2xl font-bold text-xs bg-background">
                      <SelectValue placeholder="Academic Year" />
                    </SelectTrigger>
                    <SelectContent>
                      {academicYears.map(yr => (
                        <SelectItem key={yr} value={yr} className="text-xs font-semibold">
                          {yr}
                        </SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                </div>

                <div className="space-y-1.5">
                  <Label className="text-xs font-black uppercase tracking-wider text-muted-foreground">
                    Week Start
                  </Label>
                  <Input
                    type="date"
                    value={weekStart}
                    onChange={e => setWeekStart(e.target.value)}
                    className="h-11 rounded-2xl font-bold text-xs bg-background"
                  />
                </div>

                <div className="space-y-1.5">
                  <Label className="text-xs font-black uppercase tracking-wider text-muted-foreground">
                    Week End (Auto-calculated)
                  </Label>
                  <Input
                    type="date"
                    disabled
                    value={calculatedWeekEnd}
                    className="h-11 rounded-2xl font-bold text-xs bg-muted/60 opacity-80 cursor-not-allowed"
                  />
                </div>
              </div>

              {/* Working Days Checkboxes */}
              <div className="space-y-2">
                <Label className="text-xs font-black uppercase tracking-wider text-muted-foreground">
                  Working Days
                </Label>
                <div className="grid grid-cols-2 sm:grid-cols-4 md:grid-cols-7 gap-2">
                  {ALL_WEEK_DAYS.map(day => {
                    const isChecked = workingDays.includes(day);
                    return (
                      <label
                        key={day}
                        className={`flex items-center gap-2.5 p-3 rounded-2xl border cursor-pointer select-none transition-all ${
                          isChecked
                            ? 'bg-primary/10 border-primary text-foreground font-black shadow-xs'
                            : 'bg-background hover:bg-muted/50 border-border text-muted-foreground'
                        }`}
                      >
                        <Checkbox
                          checked={isChecked}
                          onCheckedChange={() => toggleWorkingDay(day)}
                          className="data-[state=checked]:bg-primary data-[state=checked]:border-primary"
                        />
                        <span className="text-xs">{day.slice(0, 3)}</span>
                      </label>
                    );
                  })}
                </div>
              </div>

              {/* Institute Operating Hours */}
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 p-4 rounded-2xl border bg-muted/30">
                <div className="space-y-1.5">
                  <Label className="text-xs font-black uppercase tracking-wider text-muted-foreground flex items-center gap-1.5">
                    <Clock className="h-3.5 w-3.5 text-primary" /> Institute Start Time
                  </Label>
                  <Input
                    type="time"
                    value={instituteStartTime}
                    onChange={e => setInstituteStartTime(e.target.value)}
                    className="h-11 rounded-2xl font-bold text-xs bg-background"
                  />
                  <p className="text-[11px] text-muted-foreground">
                    Earliest slot available: {formatTime12h(instituteStartTime)}
                  </p>
                </div>

                <div className="space-y-1.5">
                  <Label className="text-xs font-black uppercase tracking-wider text-muted-foreground flex items-center gap-1.5">
                    <Clock className="h-3.5 w-3.5 text-primary" /> Institute End Time
                  </Label>
                  <Input
                    type="time"
                    value={instituteEndTime}
                    onChange={e => setInstituteEndTime(e.target.value)}
                    className="h-11 rounded-2xl font-bold text-xs bg-background"
                  />
                  <p className="text-[11px] text-muted-foreground">
                    Latest slot concluding: {formatTime12h(instituteEndTime)}
                  </p>
                </div>
              </div>

              {/* Lecture Duration & Gap */}
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                <div className="space-y-1.5">
                  <Label className="text-xs font-black uppercase tracking-wider text-muted-foreground">
                    Default Lecture Duration
                  </Label>
                  <Select
                    value={defaultDuration.toString()}
                    onValueChange={val => setDefaultDuration(Number(val))}
                  >
                    <SelectTrigger className="h-11 rounded-2xl font-bold text-xs bg-background">
                      <SelectValue placeholder="Duration" />
                    </SelectTrigger>
                    <SelectContent>
                      {LECTURE_DURATION_OPTIONS.map(opt => (
                        <SelectItem key={opt.value} value={opt.value.toString()} className="text-xs font-semibold">
                          {opt.label}
                        </SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                  <p className="text-[11px] text-muted-foreground">Standard duration for each scheduled lecture</p>
                </div>

                <div className="space-y-1.5">
                  <Label className="text-xs font-black uppercase tracking-wider text-muted-foreground">
                    Gap Between Lectures
                  </Label>
                  <Select
                    value={gapMinutes.toString()}
                    onValueChange={val => setGapMinutes(Number(val))}
                  >
                    <SelectTrigger className="h-11 rounded-2xl font-bold text-xs bg-background">
                      <SelectValue placeholder="Gap" />
                    </SelectTrigger>
                    <SelectContent>
                      {GAP_OPTIONS.map(opt => (
                        <SelectItem key={opt.value} value={opt.value.toString()} className="text-xs font-semibold">
                          {opt.label}
                        </SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                  <p className="text-[11px] text-muted-foreground">Required recess between sequential batch lectures</p>
                </div>
              </div>
            </div>
          )}

          {/* ══════════════════════════════════════════════════════════
              STEP 2: BATCH CONFIGURATION
          ══════════════════════════════════════════════════════════ */}
          {currentStep === 2 && (
            <div className="space-y-5 animate-in fade-in-50 duration-200">
              <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 border-b pb-4">
                <div>
                  <h3 className="text-base font-black text-foreground">Select Batches</h3>
                  <p className="text-xs text-muted-foreground">
                    Configure preferred lecture windows for each batch. (Combined classes like "Class 7 & 8" are handled as 1 cohesive batch).
                  </p>
                </div>
                <div className="flex items-center gap-2">
                  <Button
                    type="button"
                    variant="outline"
                    size="sm"
                    onClick={() => toggleAllBatches(true)}
                    className="text-xs font-bold rounded-xl"
                  >
                    Select All
                  </Button>
                  <Button
                    type="button"
                    variant="outline"
                    size="sm"
                    onClick={() => toggleAllBatches(false)}
                    className="text-xs font-bold rounded-xl"
                  >
                    Clear All
                  </Button>
                </div>
              </div>

              {batches.length === 0 ? (
                <div className="p-8 text-center text-muted-foreground border-2 border-dashed rounded-2xl">
                  <Users className="h-8 w-8 mx-auto mb-2 opacity-40" />
                  <p className="font-bold text-sm">No batches found.</p>
                  <p className="text-xs">Create batches in Admin Dashboard before generating timetables.</p>
                </div>
              ) : (
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  {batches.map(b => {
                    const cfg = batchConfigs[b.id];
                    const isSelected = !!cfg?.selected;

                    return (
                      <div
                        key={b.id}
                        className={`p-4 rounded-2xl border-2 transition-all space-y-3 ${
                          isSelected
                            ? 'bg-card border-primary/40 shadow-sm'
                            : 'bg-muted/20 border-border opacity-70'
                        }`}
                      >
                        <div className="flex items-center justify-between">
                          <label className="flex items-center gap-2.5 cursor-pointer font-black text-sm text-foreground">
                            <Checkbox
                              checked={isSelected}
                              onCheckedChange={() => toggleBatchSelected(b.id)}
                              className="data-[state=checked]:bg-primary data-[state=checked]:border-primary"
                            />
                            <span>{b.name}</span>
                            {b.year && (
                              <Badge variant="secondary" className="text-[10px] font-bold">
                                {b.year}
                              </Badge>
                            )}
                          </label>
                          {cfg?.isCombinedBatch && (
                            <Badge className="text-[10px] font-bold bg-primary text-primary-foreground">
                              Combined Batch
                            </Badge>
                          )}
                        </div>

                        {isSelected && (
                          <div className="space-y-3 pt-2 border-t text-xs">
                            <div className="grid grid-cols-2 gap-2.5">
                              <div className="space-y-1">
                                <Label className="text-[10px] font-black uppercase text-muted-foreground">
                                  Preferred Start Time
                                </Label>
                                <Input
                                  type="time"
                                  value={cfg.preferredStartTime}
                                  onChange={e => updateBatchScheduleTimes(b.id, 'preferredStartTime', e.target.value)}
                                  className="h-9 text-xs rounded-xl font-bold bg-background"
                                />
                              </div>

                              <div className="space-y-1">
                                <Label className="text-[10px] font-black uppercase text-muted-foreground">
                                  Preferred End Time
                                </Label>
                                <Input
                                  type="time"
                                  value={cfg.preferredEndTime}
                                  onChange={e => updateBatchScheduleTimes(b.id, 'preferredEndTime', e.target.value)}
                                  className="h-9 text-xs rounded-xl font-bold bg-background"
                                />
                              </div>
                            </div>

                            <div className="grid grid-cols-1 sm:grid-cols-2 gap-2.5 pt-1 items-center">
                              <div className="space-y-1">
                                <Label className="text-[10px] font-black uppercase text-muted-foreground">
                                  Default Lectures / Wk
                                </Label>
                                <select
                                  value={(cfg.defaultLecturesPerWeek || 2).toString()}
                                  onChange={e => {
                                    const val = Number(e.target.value);
                                    setBatchConfigs(prev => {
                                      const cur = prev[b.id];
                                      if (!cur) return prev;
                                      const updatedSubs = { ...cur.subjectConfigs };
                                      Object.keys(updatedSubs).forEach(sName => {
                                        updatedSubs[sName] = { ...updatedSubs[sName], lecturesPerWeek: val };
                                      });
                                      return {
                                        ...prev,
                                        [b.id]: {
                                          ...cur,
                                          defaultLecturesPerWeek: val,
                                          subjectConfigs: updatedSubs,
                                        },
                                      };
                                    });
                                  }}
                                  className="h-9 w-full rounded-xl border border-input bg-background px-2.5 font-bold text-xs"
                                >
                                  {[1, 2, 3, 4, 5, 6].map(n => (
                                    <option key={n} value={n}>
                                      {n} {n === 1 ? 'lecture / week' : 'lectures / week'}
                                    </option>
                                  ))}
                                </select>
                              </div>

                              <label className="flex items-center gap-2 cursor-pointer select-none pt-2 sm:pt-4">
                                <Checkbox
                                  checked={!!cfg.isCombinedBatch}
                                  onCheckedChange={checked => {
                                    setBatchConfigs(prev => {
                                      const cur = prev[b.id];
                                      if (!cur) return prev;
                                      return {
                                        ...prev,
                                        [b.id]: {
                                          ...cur,
                                          isCombinedBatch: !!checked,
                                        },
                                      };
                                    });
                                  }}
                                  className="data-[state=checked]:bg-primary data-[state=checked]:border-primary"
                                />
                                <div>
                                  <span className="font-black text-xs text-foreground block leading-tight">
                                    Combined Batch
                                  </span>
                                  <span className="text-[10px] text-muted-foreground leading-tight block">
                                    Assign two subjects at the same time
                                  </span>
                                </div>
                              </label>
                            </div>
                          </div>
                        )}
                      </div>
                    );
                  })}
                </div>
              )}
            </div>
          )}

          {/* ══════════════════════════════════════════════════════════
              STEP 3: SUBJECT CONFIGURATION & MULTI-TEACHER
          ══════════════════════════════════════════════════════════ */}
          {currentStep === 3 && (
            <div className="space-y-5 animate-in fade-in-50 duration-200">
              <div className="border-b pb-4">
                <h3 className="text-base font-black text-foreground">Configure Subjects per Batch</h3>
                <p className="text-xs text-muted-foreground">
                  Specify how many lectures to schedule each week for each subject, and optionally enable co-teaching (assign two teachers).
                </p>
              </div>

              {selectedBatchesList.length === 0 ? (
                <div className="p-8 text-center text-muted-foreground border-2 border-dashed rounded-2xl">
                  <p className="font-bold text-sm">No batches selected.</p>
                  <Button
                    variant="outline"
                    size="sm"
                    onClick={() => setCurrentStep(2)}
                    className="mt-2 text-xs rounded-xl"
                  >
                    Go Back & Select Batches
                  </Button>
                </div>
              ) : (
                <div className="space-y-6">
                  {/* Batch Selector Tabs for Quick Access */}
                  <div className="flex flex-wrap gap-2">
                    {selectedBatchesList.map(b => (
                      <button
                        key={b.batchId}
                        type="button"
                        onClick={() => setActiveSubjectBatchId(b.batchId)}
                        className={`px-3 py-1.5 rounded-xl text-xs font-extrabold transition-all border ${
                          activeSubjectBatchId === b.batchId
                            ? 'bg-primary text-primary-foreground border-primary shadow-xs'
                            : 'bg-muted/50 border-border text-muted-foreground hover:text-foreground'
                        }`}
                      >
                        {b.batchName}
                      </button>
                    ))}
                  </div>

                  {/* Active Batch's Subjects Configuration Card */}
                  {(() => {
                    const currentBatchConfig = batchConfigs[activeSubjectBatchId] || selectedBatchesList[0];
                    if (!currentBatchConfig) return null;

                    return (
                      <div className="p-5 rounded-2xl border-2 bg-card space-y-4 shadow-xs">
                        <div className="flex items-center justify-between pb-3 border-b">
                          <div>
                            <h4 className="font-black text-base text-foreground uppercase tracking-wide flex items-center gap-2">
                              <BookOpen className="h-4 w-4 text-primary" />
                              {currentBatchConfig.batchName}
                            </h4>
                            <p className="text-[11px] text-muted-foreground">
                              Select subjects and frequency. Teachers assigned to these subjects will be scheduled automatically.
                            </p>
                          </div>
                        </div>

                        {currentBatchConfig.isCombinedBatch ? (
                          <div className="p-3.5 rounded-xl bg-primary/10 border border-primary/30 flex items-center justify-between gap-3">
                            <div className="flex items-center gap-2.5">
                              <Sparkles className="h-5 w-5 text-primary shrink-0" />
                              <div>
                                <div className="flex items-center gap-2">
                                  <p className="text-xs font-black text-foreground">
                                    Combined Batch Active
                                  </p>
                                  <Badge className="text-[10px] font-bold bg-primary text-primary-foreground">
                                    2 Subjects Scheduled Simultaneously
                                  </Badge>
                                </div>
                                <p className="text-[11px] text-muted-foreground mt-0.5">
                                  Two subjects will be scheduled at the exact same time slot with dedicated teachers (e.g. Mathematics & Science simultaneously).
                                </p>
                              </div>
                            </div>
                            <label className="flex items-center gap-2 cursor-pointer shrink-0">
                              <Checkbox
                                checked={currentBatchConfig.isCombinedBatch}
                                onCheckedChange={checked => {
                                  setBatchConfigs(prev => ({
                                    ...prev,
                                    [currentBatchConfig.batchId]: {
                                      ...prev[currentBatchConfig.batchId],
                                      isCombinedBatch: !!checked,
                                    },
                                  }));
                                }}
                                className="data-[state=checked]:bg-primary data-[state=checked]:border-primary"
                              />
                              <span className="text-xs font-bold">Enabled</span>
                            </label>
                          </div>
                        ) : (
                          <div className="flex items-center justify-between p-2.5 rounded-xl bg-muted/40 border">
                            <span className="text-xs text-muted-foreground font-semibold">
                              Want two subjects scheduled simultaneously in the same slot?
                            </span>
                            <label className="flex items-center gap-2 cursor-pointer">
                              <Checkbox
                                checked={!!currentBatchConfig.isCombinedBatch}
                                onCheckedChange={checked => {
                                  setBatchConfigs(prev => ({
                                    ...prev,
                                    [currentBatchConfig.batchId]: {
                                      ...prev[currentBatchConfig.batchId],
                                      isCombinedBatch: !!checked,
                                    },
                                  }));
                                }}
                                className="data-[state=checked]:bg-primary data-[state=checked]:border-primary"
                              />
                              <span className="text-xs font-black text-primary">
                                Enable Combined Batch
                              </span>
                            </label>
                          </div>
                        )}

                        {subjects.length === 0 ? (
                          <p className="text-xs text-muted-foreground py-4 text-center">
                            No subjects found in institute settings. Add subjects first.
                          </p>
                        ) : (
                          <div className="grid grid-cols-1 gap-3 max-h-[46vh] overflow-y-auto pr-1">
                            {subjects.map(s => {
                              const sCfg = currentBatchConfig.subjectConfigs[s.name] || {
                                subjectName: s.name,
                                selected: true,
                                lecturesPerWeek: 2,
                                assignTwoTeachers: false,
                              };
                              const eligibleTeachers = findEligibleTeachers(s.name, teachers);

                              return (
                                <div
                                  key={s.id}
                                  className={`p-3.5 rounded-2xl border transition-all ${
                                    sCfg.selected
                                      ? 'bg-background border-border shadow-xs'
                                      : 'bg-muted/20 border-border/50 opacity-60'
                                  }`}
                                >
                                  <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3">
                                    {/* Subject Title & Eligible Teachers Info */}
                                    <div className="flex items-start gap-3">
                                      <Checkbox
                                        checked={sCfg.selected}
                                        onCheckedChange={checked =>
                                          updateSubjectConfig(currentBatchConfig.batchId, s.name, {
                                            selected: !!checked,
                                          })
                                        }
                                        className="mt-1 data-[state=checked]:bg-primary data-[state=checked]:border-primary"
                                      />
                                      <div>
                                        <p className="font-black text-sm text-foreground">{s.name}</p>
                                        <div className="flex flex-wrap items-center gap-1.5 mt-0.5">
                                          {eligibleTeachers.length > 0 ? (
                                            <span className="text-[10px] text-muted-foreground font-semibold flex items-center gap-1">
                                              <Users className="h-3 w-3 text-primary/70" />
                                              {eligibleTeachers.map(t => t.name).join(', ')}
                                            </span>
                                          ) : (
                                            <span className="text-[10px] text-amber-600 dark:text-amber-400 font-bold flex items-center gap-1">
                                              <AlertTriangle className="h-3 w-3" /> No teachers assigned to {s.name}
                                            </span>
                                          )}
                                        </div>
                                      </div>
                                    </div>

                                    {/* Controls: Lectures per Week & Two Teachers Checkbox */}
                                    {sCfg.selected && (
                                      <div className="flex flex-wrap items-center gap-3 sm:self-center">
                                        <div className="flex items-center gap-2">
                                          <Label className="text-xs font-bold whitespace-nowrap text-muted-foreground">
                                            Lectures / wk:
                                          </Label>
                                          <Select
                                            value={sCfg.lecturesPerWeek.toString()}
                                            onValueChange={val =>
                                              updateSubjectConfig(currentBatchConfig.batchId, s.name, {
                                                lecturesPerWeek: Number(val),
                                              })
                                            }
                                          >
                                            <SelectTrigger className="h-9 w-28 rounded-xl font-bold text-xs bg-background">
                                              <SelectValue />
                                            </SelectTrigger>
                                            <SelectContent>
                                              {[1, 2, 3, 4, 5].map(n => (
                                                <SelectItem key={n} value={n.toString()} className="text-xs font-semibold">
                                                  {n} {n === 1 ? 'lecture' : 'lectures'}
                                                </SelectItem>
                                              ))}
                                              <SelectItem
                                                value={workingDays.length.toString()}
                                                className="text-xs font-semibold text-primary"
                                              >
                                                Every day ({workingDays.length})
                                              </SelectItem>
                                            </SelectContent>
                                          </Select>
                                        </div>

                                        {/* Multi-Teacher Option */}
                                        <label className="flex items-center gap-2 cursor-pointer bg-muted/60 hover:bg-muted p-2 rounded-xl text-xs select-none">
                                          <Checkbox
                                            checked={sCfg.assignTwoTeachers}
                                            onCheckedChange={checked =>
                                              updateSubjectConfig(currentBatchConfig.batchId, s.name, {
                                                assignTwoTeachers: !!checked,
                                              })
                                            }
                                            className="data-[state=checked]:bg-primary data-[state=checked]:border-primary"
                                          />
                                          <span className="font-extrabold text-[11px] text-foreground">
                                            Assign 2 Teachers
                                          </span>
                                        </label>
                                      </div>
                                    )}
                                  </div>
                                </div>
                              );
                            })}
                          </div>
                        )}
                      </div>
                    );
                  })()}
                </div>
              )}
            </div>
          )}

          {/* ══════════════════════════════════════════════════════════
              STEP 4: GENERATING ANIMATION
          ══════════════════════════════════════════════════════════ */}
          {currentStep === 4 && (
            <div className="py-12 px-4 flex flex-col items-center justify-center text-center space-y-6 animate-in fade-in-50 duration-200">
              <div className="relative">
                <div className="h-20 w-20 rounded-full bg-primary/10 border-4 border-primary/30 flex items-center justify-center animate-spin">
                  <Wand2 className="h-8 w-8 text-primary animate-pulse" />
                </div>
              </div>

              <div>
                <h3 className="text-xl font-black text-foreground">✨ Generating Timetable...</h3>
                <p className="text-xs text-muted-foreground mt-1 max-w-md mx-auto">
                  Running deterministic constraint-based algorithm to allocate lectures, verify teacher qualifications, and eliminate room overlaps.
                </p>
              </div>

              {/* Progressive Checklist of Generator Stages */}
              <div className="w-full max-w-sm bg-muted/40 p-4 rounded-2xl border space-y-2.5 text-left text-xs">
                {GENERATION_STEPS.map((step, idx) => {
                  const isDone = generationStepIndex >= idx;
                  const isCurrent = generationStepIndex === idx;

                  return (
                    <div
                      key={step.id}
                      className={`flex items-center justify-between transition-all ${
                        isDone ? 'text-foreground font-bold' : 'text-muted-foreground opacity-40'
                      }`}
                    >
                      <span className="flex items-center gap-2">
                        {isDone ? (
                          <CheckCircle2 className="h-4 w-4 text-emerald-600 dark:text-emerald-400" />
                        ) : (
                          <div className="h-4 w-4 rounded-full border border-muted-foreground/40" />
                        )}
                        {step.label}
                      </span>
                      {isCurrent && (
                        <span className="text-[10px] font-mono text-primary animate-pulse">processing...</span>
                      )}
                    </div>
                  );
                })}
              </div>
            </div>
          )}

          {/* ══════════════════════════════════════════════════════════
              STEP 5: REVIEW, VALIDATION, AND MANUAL EDITING
          ══════════════════════════════════════════════════════════ */}
          {currentStep === 5 && generatedResult && (
            <div className="space-y-6 animate-in fade-in-50 duration-200">
              {/* Summary Stats Banner */}
              <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-6 gap-3">
                <div className="p-3 bg-muted/50 rounded-2xl border text-center">
                  <p className="text-[10px] font-black uppercase text-muted-foreground">Batches</p>
                  <p className="text-xl font-black text-foreground">{generatedResult.stats.batchesCount}</p>
                </div>
                <div className="p-3 bg-muted/50 rounded-2xl border text-center">
                  <p className="text-[10px] font-black uppercase text-muted-foreground">Lectures</p>
                  <p className="text-xl font-black text-primary">{generatedResult.stats.lecturesCount}</p>
                </div>
                <div className="p-3 bg-muted/50 rounded-2xl border text-center">
                  <p className="text-[10px] font-black uppercase text-muted-foreground">Teachers</p>
                  <p className="text-xl font-black text-foreground">{generatedResult.stats.teachersCount}</p>
                </div>
                <div className="p-3 bg-muted/50 rounded-2xl border text-center">
                  <p className="text-[10px] font-black uppercase text-muted-foreground">Rooms</p>
                  <p className="text-xl font-black text-foreground">{generatedResult.stats.roomsCount}</p>
                </div>
                <div
                  className={`p-3 rounded-2xl border text-center ${
                    generatedResult.stats.conflictsCount === 0
                      ? 'bg-emerald-500/10 border-emerald-500/30 text-emerald-700 dark:text-emerald-400'
                      : 'bg-red-500/10 border-red-500/30 text-red-700 dark:text-red-400'
                  }`}
                >
                  <p className="text-[10px] font-black uppercase">Conflicts</p>
                  <p className="text-xl font-black">{generatedResult.stats.conflictsCount}</p>
                </div>
                <div
                  className={`p-3 rounded-2xl border text-center ${
                    generatedResult.stats.unscheduledCount === 0
                      ? 'bg-muted/50 text-foreground'
                      : 'bg-amber-500/10 border-amber-500/30 text-amber-700 dark:text-amber-400'
                  }`}
                >
                  <p className="text-[10px] font-black uppercase">Unscheduled</p>
                  <p className="text-xl font-black">{generatedResult.stats.unscheduledCount}</p>
                </div>
              </div>

              {/* UNSCHEDULED LECTURES ALERT (Requirement: Never silently remove lectures) */}
              {generatedResult.unscheduled.length > 0 && (
                <div className="p-4 rounded-2xl border-2 border-amber-500/40 bg-amber-500/10 space-y-3">
                  <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2">
                    <div className="flex items-center gap-2 text-amber-800 dark:text-amber-300 font-black text-sm">
                      <AlertTriangle className="h-5 w-5 shrink-0" />
                      <span>{generatedResult.unscheduled.length} lecture(s) could not be scheduled</span>
                    </div>
                    <div className="flex items-center gap-2">
                      <Button
                        type="button"
                        variant="outline"
                        size="sm"
                        onClick={() => setCurrentStep(1)}
                        className="text-xs font-bold rounded-xl h-8 border-amber-500/40 text-amber-800 dark:text-amber-300"
                      >
                        Adjust Settings
                      </Button>
                      <Button
                        type="button"
                        variant="outline"
                        size="sm"
                        onClick={handleRegenerate}
                        className="text-xs font-bold rounded-xl h-8 border-amber-500/40 text-amber-800 dark:text-amber-300"
                      >
                        Regenerate
                      </Button>
                    </div>
                  </div>

                  <div className="divide-y divide-amber-500/20 max-h-36 overflow-y-auto text-xs pr-1">
                    {generatedResult.unscheduled.map(u => (
                      <div key={u.id} className="py-2 flex items-center justify-between gap-4">
                        <div>
                          <span className="font-black text-foreground">{u.subjectName}</span>
                          <span className="text-muted-foreground ml-1.5">({u.batchName} • Lecture #{u.lectureNum})</span>
                        </div>
                        <span className="text-[11px] text-amber-700 dark:text-amber-300 font-semibold">{u.reason}</span>
                      </div>
                    ))}
                  </div>
                </div>
              )}

              {/* CONFLICTS ALERT (Requirement: Zero-Conflict Save Rule) */}
              {!generatedResult.validation.isValid && (
                <div className="p-4 rounded-2xl border-2 border-red-500/40 bg-red-500/10 space-y-3">
                  <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2">
                    <div className="flex items-center gap-2 text-red-800 dark:text-red-300 font-black text-sm">
                      <AlertCircle className="h-5 w-5 shrink-0" />
                      <span>⚠ Timetable requires attention ({generatedResult.validation.totalConflicts} hard conflicts)</span>
                    </div>
                    <Button
                      type="button"
                      onClick={handleAutoFix}
                      className="text-xs font-bold rounded-xl h-8 bg-red-600 hover:bg-red-700 text-white gap-1.5"
                    >
                      <Wand2 className="h-3.5 w-3.5" /> Fix Automatically
                    </Button>
                  </div>

                  <div className="divide-y divide-red-500/20 max-h-40 overflow-y-auto text-xs pr-1">
                    {generatedResult.validation.issues.map(iss => (
                      <div key={iss.id} className="py-2 flex items-center justify-between gap-4">
                        <div>
                          <Badge variant="destructive" className="text-[9px] uppercase font-bold mr-2">
                            {iss.type.replace('_', ' ')}
                          </Badge>
                          <span className="font-semibold text-foreground">{iss.message}</span>
                        </div>
                        <span className="text-[10px] font-mono text-muted-foreground shrink-0">
                          {iss.day} • {iss.timeRange}
                        </span>
                      </div>
                    ))}
                  </div>
                </div>
              )}

              {/* Preview Controls Bar: Day Filter, Batch Filter, + Add Lecture */}
              <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 border-b pb-4">
                <div className="flex flex-wrap items-center gap-2">
                  {/* Day Filter */}
                  <Select value={previewDayFilter} onValueChange={setPreviewDayFilter}>
                    <SelectTrigger className="h-9 w-32 rounded-xl text-xs font-bold bg-background">
                      <SelectValue placeholder="Filter Day" />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="all" className="text-xs font-semibold">All Days</SelectItem>
                      {workingDays.map(d => (
                        <SelectItem key={d} value={d} className="text-xs font-semibold">{d}</SelectItem>
                      ))}
                    </SelectContent>
                  </Select>

                  {/* Batch Filter */}
                  <Select value={previewBatchFilter} onValueChange={setPreviewBatchFilter}>
                    <SelectTrigger className="h-9 w-36 rounded-xl text-xs font-bold bg-background">
                      <SelectValue placeholder="Filter Batch" />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="all" className="text-xs font-semibold">All Batches</SelectItem>
                      {selectedBatchesList.map(b => (
                        <SelectItem key={b.batchId} value={b.batchId} className="text-xs font-semibold">
                          {b.batchName}
                        </SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                </div>

                <div className="flex items-center gap-2">
                  <Button
                    type="button"
                    variant="outline"
                    size="sm"
                    onClick={() => {
                      setIsManualAddOpen(true);
                      setEditDay(workingDays[0] || 'Monday');
                      setEditStartTime(instituteStartTime);
                      setEditEndTime(minutesToTime(timeToMinutes(instituteStartTime) + defaultDuration));
                      setEditSubjectName(subjects[0]?.name || '');
                      setEditSubject2Name('');
                      setEditTeacher1Id(teachers[0]?.id || '');
                      setEditTeacher2Id('');
                      setEditRoomName(availableRooms[0] || 'Room 1');
                      setEditBatchId(selectedBatchesList[0]?.batchId || '');
                    }}
                    className="h-9 text-xs font-bold rounded-xl gap-1.5"
                  >
                    <Plus className="h-3.5 w-3.5" /> Add Lecture
                  </Button>
                  <Button
                    type="button"
                    variant="outline"
                    size="sm"
                    onClick={handleRegenerate}
                    className="h-9 text-xs font-bold rounded-xl gap-1.5"
                  >
                    <RotateCcw className="h-3.5 w-3.5" /> Regenerate
                  </Button>
                  {generatedResult.lectures.length > 0 && (
                    <Button
                      type="button"
                      variant="outline"
                      size="sm"
                      onClick={() => {
                        setGeneratedResult(prev => {
                          if (!prev) return null;
                          return {
                            ...prev,
                            lectures: [],
                            validation: {
                              isValid: true,
                              batchConflicts: 0,
                              teacherConflicts: 0,
                              additionalTeacherConflicts: 0,
                              roomConflicts: 0,
                              timeConflicts: 0,
                              gapConflicts: 0,
                              teacherSubjectConflicts: 0,
                              duplicateConflicts: 0,
                              totalConflicts: 0,
                              issues: [],
                            },
                            stats: {
                              ...prev.stats,
                              lecturesCount: 0,
                              conflictsCount: 0,
                            },
                          };
                        });
                        toast.info('All lectures cleared from preview.');
                      }}
                      className="h-9 text-xs font-bold rounded-xl gap-1.5 text-destructive hover:bg-destructive/10 hover:text-destructive border-destructive/30"
                    >
                      <Trash2 className="h-3.5 w-3.5" /> Clear All Lectures
                    </Button>
                  )}
                </div>
              </div>

              {/* Grouped Lecture Cards Preview */}
              {filteredPreviewLectures.length === 0 ? (
                <div className="py-12 text-center text-muted-foreground border-2 border-dashed rounded-2xl">
                  <p className="font-bold text-sm">No lectures found matching the filter.</p>
                </div>
              ) : (
                <div className="space-y-6 max-h-[50vh] overflow-y-auto pr-1">
                  {Object.keys(groupedPreview).map(day => {
                    const batchMap = groupedPreview[day];
                    const batchesWithLectures = Object.keys(batchMap).filter(b => batchMap[b].length > 0);
                    if (batchesWithLectures.length === 0) return null;

                    return (
                      <div key={day} className="space-y-3">
                        <div className="flex items-center gap-2">
                          <h4 className="font-black text-sm uppercase tracking-wider text-primary">
                            {day}
                          </h4>
                          <div className="h-px flex-1 bg-border" />
                        </div>

                        <div className="space-y-4">
                          {batchesWithLectures.map(bName => {
                            const lecs = batchMap[bName];

                            return (
                              <div key={bName} className="p-4 rounded-2xl border bg-card/60 space-y-3 shadow-2xs">
                                <div className="flex items-center justify-between">
                                  <h5 className="font-black text-xs uppercase tracking-wide text-foreground">
                                    {bName}
                                  </h5>
                                  <span className="text-[10px] font-bold text-muted-foreground">
                                    {lecs.length} {lecs.length === 1 ? 'Lecture' : 'Lectures'}
                                  </span>
                                </div>

                                <div className="grid grid-cols-1 md:grid-cols-2 gap-2.5">
                                  {lecs.map(lec => {
                                    const teacherIds = getLectureTeacherIds(lec);
                                    const teacherNames = getLectureTeacherNames(lec);
                                    const isMultiTeacher = teacherIds.length > 1;

                                    return (
                                      <div
                                        key={lec.timetableId}
                                        className="p-3 rounded-xl border bg-background hover:border-primary/40 transition-colors flex items-center justify-between gap-3 text-xs"
                                      >
                                        <div className="space-y-1 min-w-0">
                                          <div className="flex items-center gap-2">
                                            <span className="font-mono font-black text-primary text-[11px]">
                                              {formatTimeRange12h(lec.startTime, lec.endTime)}
                                            </span>
                                            <Badge variant="outline" className="text-[10px] font-bold px-1.5 py-0">
                                              {lec.roomName || 'Room'}
                                            </Badge>
                                            {lec.subjectNames && lec.subjectNames.length > 1 && (
                                              <Badge className="text-[9px] bg-primary/15 text-primary border-primary/30 py-0 px-1.5 font-extrabold">
                                                Combined (2 Subjects)
                                              </Badge>
                                            )}
                                          </div>

                                          <p className="font-black text-foreground truncate">
                                            {lec.subjectName}
                                          </p>

                                          <div className="flex items-center gap-1.5 text-[11px] text-muted-foreground">
                                            <Users className="h-3 w-3 text-primary/70 shrink-0" />
                                            <span className="truncate">
                                              {formatLectureSubjectWithTeachers(lec)}
                                            </span>
                                            {isMultiTeacher && (!lec.subjectNames || lec.subjectNames.length <= 1) && (
                                              <Badge className="text-[9px] bg-primary/10 text-primary border-primary/30 py-0 px-1 font-bold">
                                                Co-Teaching
                                              </Badge>
                                            )}
                                          </div>
                                        </div>

                                        <div className="flex items-center gap-1 shrink-0">
                                          <Button
                                            type="button"
                                            variant="ghost"
                                            size="icon"
                                            onClick={() => handleOpenEditLecture(lec)}
                                            className="h-8 w-8 rounded-lg text-muted-foreground hover:text-primary"
                                            title="Edit lecture"
                                          >
                                            <Edit2 className="h-3.5 w-3.5" />
                                          </Button>
                                          <Button
                                            type="button"
                                            variant="ghost"
                                            size="icon"
                                            onClick={() => handleDeletePreviewLecture(lec.timetableId)}
                                            className="h-8 w-8 rounded-lg text-muted-foreground hover:text-destructive"
                                            title="Delete lecture"
                                          >
                                            <Trash2 className="h-3.5 w-3.5" />
                                          </Button>
                                        </div>
                                      </div>
                                    );
                                  })}
                                </div>
                              </div>
                            );
                          })}
                        </div>
                      </div>
                    );
                  })}
                </div>
              )}
            </div>
          )}
        </div>

        {/* Modal Footer Controls */}
        <div className="p-4 sm:p-5 border-t bg-muted/30 sticky bottom-0 z-20 backdrop-blur-md flex items-center justify-between gap-3">
          {currentStep === 1 && (
            <>
              <Button
                type="button"
                variant="outline"
                onClick={() => onOpenChange(false)}
                className="text-xs font-bold rounded-xl"
              >
                Cancel
              </Button>
              <Button
                type="button"
                onClick={() => setCurrentStep(2)}
                className="text-xs font-black rounded-xl gap-2 bg-primary text-primary-foreground hover:bg-primary/90"
              >
                Next: Batches <ArrowRight className="h-4 w-4" />
              </Button>
            </>
          )}

          {currentStep === 2 && (
            <>
              <Button
                type="button"
                variant="outline"
                onClick={() => setCurrentStep(1)}
                className="text-xs font-bold rounded-xl gap-2"
              >
                <ArrowLeft className="h-4 w-4" /> Back
              </Button>
              <Button
                type="button"
                onClick={() => {
                  if (selectedBatchesList.length === 0) {
                    toast.error('Please select at least one batch.');
                    return;
                  }
                  setCurrentStep(3);
                }}
                className="text-xs font-black rounded-xl gap-2 bg-primary text-primary-foreground hover:bg-primary/90"
              >
                Next: Subjects <ArrowRight className="h-4 w-4" />
              </Button>
            </>
          )}

          {currentStep === 3 && (
            <>
              <Button
                type="button"
                variant="outline"
                onClick={() => setCurrentStep(2)}
                className="text-xs font-bold rounded-xl gap-2"
              >
                <ArrowLeft className="h-4 w-4" /> Back
              </Button>
              <Button
                type="button"
                onClick={handleStartGeneration}
                className="text-xs font-black rounded-xl gap-2 bg-primary text-primary-foreground hover:bg-primary/90 shadow-sm"
              >
                <Sparkles className="h-4 w-4" /> Generate Timetable
              </Button>
            </>
          )}

          {currentStep === 4 && (
            <div className="w-full text-center text-xs font-bold text-muted-foreground animate-pulse">
              Computing optimal schedules...
            </div>
          )}

          {currentStep === 5 && generatedResult && (
            <>
              <Button
                type="button"
                variant="outline"
                onClick={() => setCurrentStep(3)}
                className="text-xs font-bold rounded-xl gap-1.5"
              >
                <ArrowLeft className="h-4 w-4" /> Adjust Settings
              </Button>

              <div className="flex items-center gap-2">
                <Button
                  type="button"
                  disabled={!generatedResult.validation.isValid || isSavingToDb}
                  onClick={handleSaveToDatabase}
                  className={`text-xs font-black rounded-xl gap-2 shadow-sm ${
                    generatedResult.validation.isValid
                      ? 'bg-primary text-primary-foreground hover:bg-primary/90'
                      : 'bg-muted text-muted-foreground opacity-50 cursor-not-allowed'
                  }`}
                >
                  <CheckCircle2 className="h-4 w-4" />
                  {isSavingToDb ? 'Saving Timetable...' : 'Save Timetable'}
                </Button>
              </div>
            </>
          )}
        </div>

        {/* ── Sub-dialog: Edit Single Lecture in Review ── */}
        <Dialog open={!!editingLecture} onOpenChange={open => !open && setEditingLecture(null)}>
          <DialogContent className="max-w-md sm:rounded-2xl">
            <DialogHeader>
              <DialogTitle className="text-base font-black">Edit Lecture</DialogTitle>
              <DialogDescription className="text-xs">
                Modifying time, room, or teacher will immediately re-validate for conflicts.
              </DialogDescription>
            </DialogHeader>

            <div className="space-y-3 pt-2 text-xs">
              <div className="grid grid-cols-2 gap-2">
                <div className="space-y-1">
                  <Label className="text-[11px] font-bold">Day</Label>
                  <Select value={editDay} onValueChange={setEditDay}>
                    <SelectTrigger className="h-9 rounded-xl font-bold text-xs">
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent>
                      {workingDays.map(d => (
                        <SelectItem key={d} value={d} className="text-xs">{d}</SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                </div>

                <div className="space-y-1">
                  <Label className="text-[11px] font-bold">Room</Label>
                  <Select value={editRoomName} onValueChange={setEditRoomName}>
                    <SelectTrigger className="h-9 rounded-xl font-bold text-xs">
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent>
                      {availableRooms.map(r => (
                        <SelectItem key={r} value={r} className="text-xs">{r}</SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                </div>
              </div>

              <div className="grid grid-cols-2 gap-2">
                <div className="space-y-1">
                  <Label className="text-[11px] font-bold">Start Time</Label>
                  <Input
                    type="time"
                    value={editStartTime}
                    onChange={e => setEditStartTime(e.target.value)}
                    className="h-9 rounded-xl font-bold text-xs"
                  />
                </div>
                <div className="space-y-1">
                  <Label className="text-[11px] font-bold">End Time</Label>
                  <Input
                    type="time"
                    value={editEndTime}
                    onChange={e => setEditEndTime(e.target.value)}
                    className="h-9 rounded-xl font-bold text-xs"
                  />
                </div>
              </div>

              <div className="grid grid-cols-1 sm:grid-cols-2 gap-2">
                <div className="space-y-1">
                  <Label className="text-[11px] font-bold">Primary Subject</Label>
                  <Select value={editSubjectName} onValueChange={setEditSubjectName}>
                    <SelectTrigger className="h-9 rounded-xl font-bold text-xs">
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent>
                      {subjects.map(s => (
                        <SelectItem key={s.id} value={s.name} className="text-xs">{s.name}</SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                </div>

                <div className="space-y-1">
                  <Label className="text-[11px] font-bold">Second Subject (Optional)</Label>
                  <Select value={editSubject2Name} onValueChange={setEditSubject2Name}>
                    <SelectTrigger className="h-9 rounded-xl font-bold text-xs">
                      <SelectValue placeholder="None (Single Subject)" />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="" className="text-xs font-bold text-muted-foreground">None</SelectItem>
                      {subjects.filter(s => s.name !== editSubjectName).map(s => (
                        <SelectItem key={s.id} value={s.name} className="text-xs">{s.name}</SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                </div>
              </div>

              <div className="grid grid-cols-2 gap-2">
                <div className="space-y-1">
                  <Label className="text-[11px] font-bold">Primary Teacher</Label>
                  <Select value={editTeacher1Id} onValueChange={setEditTeacher1Id}>
                    <SelectTrigger className="h-9 rounded-xl font-bold text-xs">
                      <SelectValue placeholder="Teacher 1" />
                    </SelectTrigger>
                    <SelectContent>
                      {teachers.map(t => (
                        <SelectItem key={t.id} value={t.id} className="text-xs">{t.name}</SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                </div>

                <div className="space-y-1">
                  <Label className="text-[11px] font-bold">Second Teacher (Optional)</Label>
                  <Select value={editTeacher2Id} onValueChange={setEditTeacher2Id}>
                    <SelectTrigger className="h-9 rounded-xl font-bold text-xs">
                      <SelectValue placeholder="None (1 Teacher)" />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="" className="text-xs font-bold text-muted-foreground">None</SelectItem>
                      {teachers.filter(t => t.id !== editTeacher1Id).map(t => (
                        <SelectItem key={t.id} value={t.id} className="text-xs">{t.name}</SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                </div>
              </div>
            </div>

            <DialogFooter className="mt-4 gap-2">
              <Button
                type="button"
                variant="outline"
                size="sm"
                onClick={() => setEditingLecture(null)}
                className="text-xs rounded-xl"
              >
                Cancel
              </Button>
              <Button
                type="button"
                size="sm"
                onClick={handleSaveEditedLecture}
                className="text-xs font-bold rounded-xl"
              >
                Save Changes
              </Button>
            </DialogFooter>
          </DialogContent>
        </Dialog>

        {/* ── Sub-dialog: Add Manual Lecture to Preview ── */}
        <Dialog open={isManualAddOpen} onOpenChange={setIsManualAddOpen}>
          <DialogContent className="max-w-md sm:rounded-2xl">
            <DialogHeader>
              <DialogTitle className="text-base font-black">Add Lecture to Preview</DialogTitle>
              <DialogDescription className="text-xs">
                Manually append a lecture before committing the timetable.
              </DialogDescription>
            </DialogHeader>

            <div className="space-y-3 pt-2 text-xs">
              <div className="space-y-1">
                <Label className="text-[11px] font-bold">Target Batch</Label>
                <Select value={editBatchId} onValueChange={setEditBatchId}>
                  <SelectTrigger className="h-9 rounded-xl font-bold text-xs">
                    <SelectValue placeholder="Select Batch" />
                  </SelectTrigger>
                  <SelectContent>
                    {batches.map(b => (
                      <SelectItem key={b.id} value={b.id} className="text-xs">{b.name}</SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>

              <div className="grid grid-cols-2 gap-2">
                <div className="space-y-1">
                  <Label className="text-[11px] font-bold">Day</Label>
                  <Select value={editDay} onValueChange={setEditDay}>
                    <SelectTrigger className="h-9 rounded-xl font-bold text-xs">
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent>
                      {workingDays.map(d => (
                        <SelectItem key={d} value={d} className="text-xs">{d}</SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                </div>

                <div className="space-y-1">
                  <Label className="text-[11px] font-bold">Room</Label>
                  <Select value={editRoomName} onValueChange={setEditRoomName}>
                    <SelectTrigger className="h-9 rounded-xl font-bold text-xs">
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent>
                      {availableRooms.map(r => (
                        <SelectItem key={r} value={r} className="text-xs">{r}</SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                </div>
              </div>

              <div className="grid grid-cols-2 gap-2">
                <div className="space-y-1">
                  <Label className="text-[11px] font-bold">Start Time</Label>
                  <Input
                    type="time"
                    value={editStartTime}
                    onChange={e => setEditStartTime(e.target.value)}
                    className="h-9 rounded-xl font-bold text-xs"
                  />
                </div>
                <div className="space-y-1">
                  <Label className="text-[11px] font-bold">End Time</Label>
                  <Input
                    type="time"
                    value={editEndTime}
                    onChange={e => setEditEndTime(e.target.value)}
                    className="h-9 rounded-xl font-bold text-xs"
                  />
                </div>
              </div>

              <div className="grid grid-cols-1 sm:grid-cols-2 gap-2">
                <div className="space-y-1">
                  <Label className="text-[11px] font-bold">Primary Subject</Label>
                  <Select value={editSubjectName} onValueChange={setEditSubjectName}>
                    <SelectTrigger className="h-9 rounded-xl font-bold text-xs">
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent>
                      {subjects.map(s => (
                        <SelectItem key={s.id} value={s.name} className="text-xs">{s.name}</SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                </div>

                <div className="space-y-1">
                  <Label className="text-[11px] font-bold">Second Subject (Optional)</Label>
                  <Select value={editSubject2Name} onValueChange={setEditSubject2Name}>
                    <SelectTrigger className="h-9 rounded-xl font-bold text-xs">
                      <SelectValue placeholder="None (Single Subject)" />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="" className="text-xs font-bold text-muted-foreground">None</SelectItem>
                      {subjects.filter(s => s.name !== editSubjectName).map(s => (
                        <SelectItem key={s.id} value={s.name} className="text-xs">{s.name}</SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                </div>
              </div>

              <div className="grid grid-cols-2 gap-2">
                <div className="space-y-1">
                  <Label className="text-[11px] font-bold">Primary Teacher</Label>
                  <Select value={editTeacher1Id} onValueChange={setEditTeacher1Id}>
                    <SelectTrigger className="h-9 rounded-xl font-bold text-xs">
                      <SelectValue placeholder="Teacher 1" />
                    </SelectTrigger>
                    <SelectContent>
                      {teachers.map(t => (
                        <SelectItem key={t.id} value={t.id} className="text-xs">{t.name}</SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                </div>

                <div className="space-y-1">
                  <Label className="text-[11px] font-bold">Second Teacher (Optional)</Label>
                  <Select value={editTeacher2Id} onValueChange={setEditTeacher2Id}>
                    <SelectTrigger className="h-9 rounded-xl font-bold text-xs">
                      <SelectValue placeholder="None (1 Teacher)" />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="" className="text-xs font-bold text-muted-foreground">None</SelectItem>
                      {teachers.filter(t => t.id !== editTeacher1Id).map(t => (
                        <SelectItem key={t.id} value={t.id} className="text-xs">{t.name}</SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                </div>
              </div>
            </div>

            <DialogFooter className="mt-4 gap-2">
              <Button
                type="button"
                variant="outline"
                size="sm"
                onClick={() => setIsManualAddOpen(false)}
                className="text-xs rounded-xl"
              >
                Cancel
              </Button>
              <Button
                type="button"
                size="sm"
                onClick={handleSaveManualLecture}
                className="text-xs font-bold rounded-xl"
              >
                Add Lecture
              </Button>
            </DialogFooter>
          </DialogContent>
        </Dialog>
      </DialogContent>
    </Dialog>
  );
};

export default TimetableAutoGenerateDialog;
